from __future__ import annotations

import argparse
from dataclasses import dataclass
from typing import Dict, Iterable, Tuple

import numpy as np
import pandas as pd

from scripts.core.paths import (
    GENERATED_CORE_DIR,
    GENERATED_PERFORMANCE_DIR,
    GENERATED_WORLD_DIR,
    INTERIM_AUDITS_DIR,
)
from scripts.core.rng import make_rng
from scripts.core.world import load_world
from scripts.generators.generate_macro_environment import (
    MACRO_COLUMNS,
    build_macro_environment_dataframe,
    validate_macro_environment,
)


# =============================================================================
# BTYT BANKING ANALYTICS — BANK NETWORK GENERATOR V4.0.1
# =============================================================================
#
# Generates:
#   1. banks.csv
#   2. bank_world_parameters.csv
#   3. bank_market_weights.csv
#   4. bank_financials.csv
#
# Consumes:
#   - data/generated/world/macro_environment.csv
#
# Optional:
#   6. bank_market_weights_audit.csv
#
# V4.0.1 calibration:
#   - Preserves the V4.0.0 architecture and 2021 initialization contract.
#   - Raises competitive-state persistence to reduce excessive mean reversion.
#   - Adds persistent strategic-shock carryover with gradual decay.
#   - Keeps ordinary annual noise moderate.
#   - Gives BROU a rare severe strategic-shock channel so leadership changes
#     are possible without making them common.
#
# V4.0.0 redesign:
#   - BTYT enters the synthetic domestic competitive system.
#   - The 2021 domestic state is generated from bounded plausibility bands.
#   - BROU is required to start as the largest domestic-system institution.
#   - Domestic competitive weights evolve annually from 2021 through 2026.
#   - Market dynamics use persistent mean-reverting latent AR-style states.
#   - Annual weights are obtained with a softmax transformation.
#   - Macro factors, systemic shocks, bank-specific shocks, and ordinary
#     idiosyncratic innovations affect competitive trajectories.
#   - BTYT has no protected growth path and may gain or lose.
#   - Domestic financial trajectories are partially linked to competitive
#     dynamics and the shared macro environment.
#   - B010 keeps one stable bank_id while its temporal display name changes:
#       2021-2025 -> HSBC Uruguay
#       2026      -> BTG Pactual Uruguay
#   - Independent deterministic RNG streams preserve modular reproducibility.
#
# All data generated by this script are synthetic.
# All code and comments are intentionally written in English.
# =============================================================================


# =============================================================================
# PROJECT PATHS
# =============================================================================

BANKS_OUTPUT = GENERATED_CORE_DIR / "banks.csv"
WORLD_PARAMS_OUTPUT = GENERATED_PERFORMANCE_DIR / "bank_world_parameters.csv"
MACRO_INPUT = GENERATED_WORLD_DIR / "macro_environment.csv"
MARKET_OUTPUT = GENERATED_PERFORMANCE_DIR / "bank_market_weights.csv"
FINANCIALS_OUTPUT = GENERATED_PERFORMANCE_DIR / "bank_financials.csv"

AUDIT_OUTPUT = INTERIM_AUDITS_DIR / "bank_market_weights_audit.csv"


# =============================================================================
# WORLD CONFIGURATION
# =============================================================================

WORLD = load_world()

WORLD_SEED = WORLD.seed
RNG_NAMESPACE = "banks"

FINANCIAL_START_YEAR = WORLD.start_date.year
FINANCIAL_END_YEAR = WORLD.end_date.year
YEARS = tuple(range(FINANCIAL_START_YEAR, FINANCIAL_END_YEAR + 1))

REPORTING_CURRENCY = "USD"

# V3-compatible streams are preserved when the conceptual module still exists.
RNG_STREAM_2021_MARKET = 101
RNG_STREAM_FOREIGN = 202
RNG_STREAM_AFFINITIES = 303
RNG_STREAM_FINANCIALS = 404

# New V4 streams.
RNG_STREAM_MARKET_PARAMS = 501
RNG_STREAM_MARKET_DYNAMICS = 503

FOREIGN_DIRICHLET_ALPHA_LOW = 2.5
FOREIGN_DIRICHLET_ALPHA_HIGH = 6.0

AFFINITY_NOISE_SD_LOW = 0.035
AFFINITY_NOISE_SD_HIGH = 0.085

INITIAL_DIRICHLET_ALPHA_LOW = 5.0
INITIAL_DIRICHLET_ALPHA_HIGH = 12.0
INITIAL_CENTER_NOISE_SD = 0.020
INITIAL_MAX_ATTEMPTS = 2_000

LOSS_YEAR_BASE_PROBABILITY = 0.035

# Guardrail for latent competitive states relative to each long-run anchor.
# This is intentionally wide enough to permit meaningful movement and shocks.
LATENT_DEVIATION_LIMIT = 0.70

# The production model should never create a domestic institution with an
# implausibly dominant synthetic weight.
MAX_DOMESTIC_WEIGHT_GUARDRAIL = 0.50

# V4.0.1 temporal calibration.
#
# A material bank-specific shock now creates a persistent strategic-state
# component. The state decays gradually instead of disappearing after one year.
STRATEGIC_SHOCK_DECAY_LOW = 0.58
STRATEGIC_SHOCK_DECAY_HIGH = 0.72

# BROU remains structurally dominant, but an unusually severe adverse event is
# allowed in a very small fraction of bank-years. This makes leadership change
# possible without making it a routine outcome.
BROU_SEVERE_SHOCK_PROBABILITY = 0.006
BROU_SEVERE_SHOCK_LOW = 0.22
BROU_SEVERE_SHOCK_HIGH = 0.38


# =============================================================================
# STRUCTURAL BANK DEFINITION
# =============================================================================

@dataclass(frozen=True)
class BankDefinition:
    bank_id: str
    bank_name: str
    bank_scope: str
    bank_type: str
    operating_country: str
    bank_profile: str
    usd_affinity: float
    business_affinity: float
    large_transfer_affinity: float
    bank_status: str = "ACTIVE"


BANKS: Tuple[BankDefinition, ...] = (
    BankDefinition(
        "B000",
        "BTYT",
        "BTYT",
        "INTERNAL",
        "Uruguay",
        "INTERNAL_GENERALIST",
        0.45,
        0.45,
        0.40,
    ),
    BankDefinition(
        "B001",
        "BROU",
        "DOMESTIC",
        "PUBLIC_BANK",
        "Uruguay",
        "GENERALIST_PUBLIC_RETAIL",
        0.42,
        0.48,
        0.42,
    ),
    BankDefinition(
        "B002",
        "BHU",
        "DOMESTIC",
        "MORTGAGE_BANK",
        "Uruguay",
        "MORTGAGE_SPECIALIST",
        0.24,
        0.18,
        0.22,
    ),
    BankDefinition(
        "B003",
        "Bandes",
        "DOMESTIC",
        "COMMERCIAL_BANK",
        "Uruguay",
        "RETAIL_NICHE",
        0.30,
        0.30,
        0.26,
    ),
    BankDefinition(
        "B004",
        "BBVA Uruguay",
        "DOMESTIC",
        "COMMERCIAL_BANK",
        "Uruguay",
        "GENERALIST_RETAIL_BUSINESS",
        0.52,
        0.58,
        0.50,
    ),
    BankDefinition(
        "B005",
        "Banco Nación",
        "DOMESTIC",
        "COMMERCIAL_BANK",
        "Uruguay",
        "REGIONAL_CROSS_BORDER",
        0.56,
        0.58,
        0.53,
    ),
    BankDefinition(
        "B006",
        "Itaú Uruguay",
        "DOMESTIC",
        "COMMERCIAL_BANK",
        "Uruguay",
        "GENERALIST_PREMIUM_BUSINESS",
        0.64,
        0.64,
        0.59,
    ),
    BankDefinition(
        "B007",
        "Santander Uruguay",
        "DOMESTIC",
        "COMMERCIAL_BANK",
        "Uruguay",
        "GENERALIST_RETAIL_BUSINESS",
        0.56,
        0.61,
        0.54,
    ),
    BankDefinition(
        "B008",
        "Banque Heritage Uruguay",
        "DOMESTIC",
        "PRIVATE_BANK",
        "Uruguay",
        "PRIVATE_WEALTH",
        0.76,
        0.43,
        0.76,
    ),
    BankDefinition(
        "B009",
        "Citibank Uruguay",
        "DOMESTIC",
        "CORPORATE_BANK",
        "Uruguay",
        "CORPORATE_USD",
        0.88,
        0.88,
        0.86,
    ),
    BankDefinition(
        "B010",
        "BTG Pactual Uruguay",
        "DOMESTIC",
        "CORPORATE_BANK",
        "Uruguay",
        "CORPORATE_WEALTH_USD",
        0.82,
        0.77,
        0.82,
    ),
    BankDefinition(
        "B011",
        "Scotiabank Uruguay",
        "DOMESTIC",
        "COMMERCIAL_BANK",
        "Uruguay",
        "GENERALIST_RETAIL_BUSINESS",
        0.57,
        0.59,
        0.53,
    ),
    BankDefinition(
        "B101",
        "JPMorgan Chase",
        "FOREIGN",
        "INTERNATIONAL_BANK",
        "United States",
        "CORPORATE_TREASURY_USD",
        0.95,
        0.94,
        0.95,
    ),
    BankDefinition(
        "B102",
        "Citibank International",
        "FOREIGN",
        "INTERNATIONAL_BANK",
        "United States",
        "CORPORATE_TREASURY_USD",
        0.94,
        0.93,
        0.94,
    ),
    BankDefinition(
        "B103",
        "Bank of America",
        "FOREIGN",
        "INTERNATIONAL_BANK",
        "United States",
        "CORPORATE_USD",
        0.89,
        0.84,
        0.86,
    ),
    BankDefinition(
        "B104",
        "Deutsche Bank",
        "FOREIGN",
        "INTERNATIONAL_BANK",
        "Germany",
        "CORPORATE_INTERNATIONAL",
        0.77,
        0.84,
        0.87,
    ),
    BankDefinition(
        "B105",
        "BNP Paribas",
        "FOREIGN",
        "INTERNATIONAL_BANK",
        "France",
        "CORPORATE_INTERNATIONAL",
        0.75,
        0.82,
        0.84,
    ),
    BankDefinition(
        "B106",
        "UBS",
        "FOREIGN",
        "INTERNATIONAL_BANK",
        "Switzerland",
        "PRIVATE_WEALTH_INTERNATIONAL",
        0.87,
        0.54,
        0.91,
    ),
    BankDefinition(
        "B107",
        "HSBC International",
        "FOREIGN",
        "INTERNATIONAL_BANK",
        "United Kingdom",
        "CROSS_BORDER_CORPORATE",
        0.86,
        0.82,
        0.82,
    ),
)


DOMESTIC_SYSTEM_IDS = (
    "B001",  # BROU
    "B007",  # Santander Uruguay
    "B006",  # Itaú Uruguay
    "B004",  # BBVA Uruguay
    "B011",  # Scotiabank Uruguay
    "B000",  # BTYT
    "B009",  # Citibank Uruguay
    "B002",  # BHU
    "B010",  # HSBC Uruguay / BTG Pactual Uruguay
    "B005",  # Banco Nación
    "B008",  # Banque Heritage Uruguay
    "B003",  # Bandes
)


# =============================================================================
# 2021 DOMESTIC INITIALIZATION CONTRACT
# =============================================================================

INITIAL_MARKET_SPECS: Dict[str, Dict[str, float]] = {
    "B001": {"low": 0.240, "center": 0.300, "high": 0.360},
    "B007": {"low": 0.100, "center": 0.150, "high": 0.210},
    "B006": {"low": 0.100, "center": 0.140, "high": 0.210},
    "B004": {"low": 0.060, "center": 0.100, "high": 0.150},
    "B011": {"low": 0.060, "center": 0.090, "high": 0.140},
    "B000": {"low": 0.025, "center": 0.050, "high": 0.080},
    "B009": {"low": 0.015, "center": 0.040, "high": 0.070},
    "B002": {"low": 0.015, "center": 0.030, "high": 0.060},
    "B010": {"low": 0.010, "center": 0.030, "high": 0.060},
    "B005": {"low": 0.010, "center": 0.025, "high": 0.050},
    "B008": {"low": 0.005, "center": 0.020, "high": 0.040},
    "B003": {"low": 0.005, "center": 0.015, "high": 0.035},
}


# =============================================================================
# DOMESTIC MARKET-DYNAMICS PARAMETERS
# =============================================================================
#
# Effects operate on the latent competitive state, not directly on shares.
# Coefficients are intentionally small relative to the latent state itself.

MARKET_DYNAMICS: Dict[str, Dict[str, float]] = {
    "B001": {
        "persistence_low": 0.90,
        "persistence_high": 0.97,
        "innovation_sd_low": 0.018,
        "innovation_sd_high": 0.032,
        "growth_beta": 0.030,
        "credit_beta": 0.018,
        "usd_beta": 0.002,
        "stress_beta": -0.025,
        "digital_beta": -0.012,
        "cross_border_beta": 0.002,
        "systemic_beta": -0.035,
        "shock_probability": 0.055,
        "shock_scale_low": 0.050,
        "shock_scale_high": 0.130,
    },
    "B007": {
        "persistence_low": 0.88,
        "persistence_high": 0.96,
        "innovation_sd_low": 0.022,
        "innovation_sd_high": 0.040,
        "growth_beta": 0.030,
        "credit_beta": 0.025,
        "usd_beta": 0.010,
        "stress_beta": -0.035,
        "digital_beta": 0.018,
        "cross_border_beta": 0.006,
        "systemic_beta": -0.045,
        "shock_probability": 0.070,
        "shock_scale_low": 0.055,
        "shock_scale_high": 0.145,
    },
    "B006": {
        "persistence_low": 0.88,
        "persistence_high": 0.96,
        "innovation_sd_low": 0.022,
        "innovation_sd_high": 0.042,
        "growth_beta": 0.032,
        "credit_beta": 0.022,
        "usd_beta": 0.020,
        "stress_beta": -0.032,
        "digital_beta": 0.022,
        "cross_border_beta": 0.008,
        "systemic_beta": -0.042,
        "shock_probability": 0.070,
        "shock_scale_low": 0.055,
        "shock_scale_high": 0.150,
    },
    "B004": {
        "persistence_low": 0.87,
        "persistence_high": 0.95,
        "innovation_sd_low": 0.024,
        "innovation_sd_high": 0.045,
        "growth_beta": 0.030,
        "credit_beta": 0.024,
        "usd_beta": 0.012,
        "stress_beta": -0.036,
        "digital_beta": 0.020,
        "cross_border_beta": 0.006,
        "systemic_beta": -0.045,
        "shock_probability": 0.075,
        "shock_scale_low": 0.060,
        "shock_scale_high": 0.155,
    },
    "B011": {
        "persistence_low": 0.87,
        "persistence_high": 0.95,
        "innovation_sd_low": 0.024,
        "innovation_sd_high": 0.046,
        "growth_beta": 0.028,
        "credit_beta": 0.023,
        "usd_beta": 0.013,
        "stress_beta": -0.037,
        "digital_beta": 0.018,
        "cross_border_beta": 0.006,
        "systemic_beta": -0.046,
        "shock_probability": 0.075,
        "shock_scale_low": 0.060,
        "shock_scale_high": 0.160,
    },
    "B000": {
        "persistence_low": 0.84,
        "persistence_high": 0.94,
        "innovation_sd_low": 0.030,
        "innovation_sd_high": 0.055,
        "growth_beta": 0.036,
        "credit_beta": 0.028,
        "usd_beta": 0.008,
        "stress_beta": -0.045,
        "digital_beta": 0.030,
        "cross_border_beta": 0.004,
        "systemic_beta": -0.052,
        "shock_probability": 0.090,
        "shock_scale_low": 0.070,
        "shock_scale_high": 0.180,
    },
    "B009": {
        "persistence_low": 0.85,
        "persistence_high": 0.94,
        "innovation_sd_low": 0.028,
        "innovation_sd_high": 0.052,
        "growth_beta": 0.020,
        "credit_beta": 0.012,
        "usd_beta": 0.040,
        "stress_beta": -0.030,
        "digital_beta": 0.006,
        "cross_border_beta": 0.030,
        "systemic_beta": -0.040,
        "shock_probability": 0.085,
        "shock_scale_low": 0.065,
        "shock_scale_high": 0.170,
    },
    "B002": {
        "persistence_low": 0.88,
        "persistence_high": 0.96,
        "innovation_sd_low": 0.022,
        "innovation_sd_high": 0.042,
        "growth_beta": 0.018,
        "credit_beta": 0.040,
        "usd_beta": -0.004,
        "stress_beta": -0.030,
        "digital_beta": -0.008,
        "cross_border_beta": -0.002,
        "systemic_beta": -0.040,
        "shock_probability": 0.060,
        "shock_scale_low": 0.050,
        "shock_scale_high": 0.135,
    },
    "B010": {
        "persistence_low": 0.84,
        "persistence_high": 0.94,
        "innovation_sd_low": 0.030,
        "innovation_sd_high": 0.055,
        "growth_beta": 0.024,
        "credit_beta": 0.010,
        "usd_beta": 0.040,
        "stress_beta": -0.028,
        "digital_beta": 0.008,
        "cross_border_beta": 0.032,
        "systemic_beta": -0.040,
        "shock_probability": 0.095,
        "shock_scale_low": 0.070,
        "shock_scale_high": 0.190,
    },
    "B005": {
        "persistence_low": 0.85,
        "persistence_high": 0.95,
        "innovation_sd_low": 0.028,
        "innovation_sd_high": 0.052,
        "growth_beta": 0.018,
        "credit_beta": 0.012,
        "usd_beta": 0.026,
        "stress_beta": -0.035,
        "digital_beta": 0.002,
        "cross_border_beta": 0.050,
        "systemic_beta": -0.042,
        "shock_probability": 0.085,
        "shock_scale_low": 0.065,
        "shock_scale_high": 0.175,
    },
    "B008": {
        "persistence_low": 0.84,
        "persistence_high": 0.94,
        "innovation_sd_low": 0.030,
        "innovation_sd_high": 0.058,
        "growth_beta": 0.018,
        "credit_beta": 0.004,
        "usd_beta": 0.042,
        "stress_beta": -0.022,
        "digital_beta": 0.002,
        "cross_border_beta": 0.030,
        "systemic_beta": -0.035,
        "shock_probability": 0.095,
        "shock_scale_low": 0.070,
        "shock_scale_high": 0.190,
    },
    "B003": {
        "persistence_low": 0.83,
        "persistence_high": 0.93,
        "innovation_sd_low": 0.032,
        "innovation_sd_high": 0.060,
        "growth_beta": 0.025,
        "credit_beta": 0.020,
        "usd_beta": 0.004,
        "stress_beta": -0.045,
        "digital_beta": 0.012,
        "cross_border_beta": 0.002,
        "systemic_beta": -0.055,
        "shock_probability": 0.100,
        "shock_scale_low": 0.075,
        "shock_scale_high": 0.200,
    },
}


# =============================================================================
# SYNTHETIC FINANCIAL PROFILE CONFIGURATION
# =============================================================================

FINANCIAL_PROFILE_PARAMS: Dict[str, Dict[str, float]] = {
    "INTERNAL_GENERALIST": {
        "asset_scale_low": 1.0e9,
        "asset_scale_high": 4.0e9,
        "deposit_ratio_low": 0.58,
        "deposit_ratio_high": 0.78,
        "loan_ratio_low": 0.42,
        "loan_ratio_high": 0.66,
        "equity_ratio_low": 0.08,
        "equity_ratio_high": 0.14,
        "revenue_asset_low": 0.045,
        "revenue_asset_high": 0.080,
        "cost_income_low": 0.52,
        "cost_income_high": 0.76,
    },
    "GENERALIST_PUBLIC_RETAIL": {
        "asset_scale_low": 5.0e9,
        "asset_scale_high": 18.0e9,
        "deposit_ratio_low": 0.64,
        "deposit_ratio_high": 0.82,
        "loan_ratio_low": 0.42,
        "loan_ratio_high": 0.64,
        "equity_ratio_low": 0.08,
        "equity_ratio_high": 0.14,
        "revenue_asset_low": 0.035,
        "revenue_asset_high": 0.065,
        "cost_income_low": 0.56,
        "cost_income_high": 0.79,
    },
    "MORTGAGE_SPECIALIST": {
        "asset_scale_low": 1.0e9,
        "asset_scale_high": 5.0e9,
        "deposit_ratio_low": 0.22,
        "deposit_ratio_high": 0.50,
        "loan_ratio_low": 0.58,
        "loan_ratio_high": 0.82,
        "equity_ratio_low": 0.10,
        "equity_ratio_high": 0.18,
        "revenue_asset_low": 0.030,
        "revenue_asset_high": 0.055,
        "cost_income_low": 0.52,
        "cost_income_high": 0.74,
    },
    "RETAIL_NICHE": {
        "asset_scale_low": 0.4e9,
        "asset_scale_high": 2.5e9,
        "deposit_ratio_low": 0.52,
        "deposit_ratio_high": 0.76,
        "loan_ratio_low": 0.44,
        "loan_ratio_high": 0.68,
        "equity_ratio_low": 0.09,
        "equity_ratio_high": 0.17,
        "revenue_asset_low": 0.040,
        "revenue_asset_high": 0.075,
        "cost_income_low": 0.56,
        "cost_income_high": 0.82,
    },
    "GENERALIST_RETAIL_BUSINESS": {
        "asset_scale_low": 2.0e9,
        "asset_scale_high": 10.0e9,
        "deposit_ratio_low": 0.58,
        "deposit_ratio_high": 0.80,
        "loan_ratio_low": 0.44,
        "loan_ratio_high": 0.69,
        "equity_ratio_low": 0.08,
        "equity_ratio_high": 0.15,
        "revenue_asset_low": 0.040,
        "revenue_asset_high": 0.072,
        "cost_income_low": 0.50,
        "cost_income_high": 0.73,
    },
    "REGIONAL_CROSS_BORDER": {
        "asset_scale_low": 0.8e9,
        "asset_scale_high": 4.0e9,
        "deposit_ratio_low": 0.48,
        "deposit_ratio_high": 0.72,
        "loan_ratio_low": 0.38,
        "loan_ratio_high": 0.62,
        "equity_ratio_low": 0.09,
        "equity_ratio_high": 0.17,
        "revenue_asset_low": 0.038,
        "revenue_asset_high": 0.070,
        "cost_income_low": 0.52,
        "cost_income_high": 0.76,
    },
    "GENERALIST_PREMIUM_BUSINESS": {
        "asset_scale_low": 2.5e9,
        "asset_scale_high": 11.0e9,
        "deposit_ratio_low": 0.56,
        "deposit_ratio_high": 0.78,
        "loan_ratio_low": 0.42,
        "loan_ratio_high": 0.66,
        "equity_ratio_low": 0.09,
        "equity_ratio_high": 0.16,
        "revenue_asset_low": 0.043,
        "revenue_asset_high": 0.078,
        "cost_income_low": 0.46,
        "cost_income_high": 0.69,
    },
    "PRIVATE_WEALTH": {
        "asset_scale_low": 0.6e9,
        "asset_scale_high": 4.5e9,
        "deposit_ratio_low": 0.46,
        "deposit_ratio_high": 0.70,
        "loan_ratio_low": 0.25,
        "loan_ratio_high": 0.48,
        "equity_ratio_low": 0.11,
        "equity_ratio_high": 0.20,
        "revenue_asset_low": 0.045,
        "revenue_asset_high": 0.085,
        "cost_income_low": 0.42,
        "cost_income_high": 0.67,
    },
    "CORPORATE_USD": {
        "asset_scale_low": 1.5e9,
        "asset_scale_high": 8.0e9,
        "deposit_ratio_low": 0.42,
        "deposit_ratio_high": 0.68,
        "loan_ratio_low": 0.28,
        "loan_ratio_high": 0.56,
        "equity_ratio_low": 0.09,
        "equity_ratio_high": 0.17,
        "revenue_asset_low": 0.038,
        "revenue_asset_high": 0.073,
        "cost_income_low": 0.40,
        "cost_income_high": 0.65,
    },
    "CORPORATE_WEALTH_USD": {
        "asset_scale_low": 1.0e9,
        "asset_scale_high": 7.0e9,
        "deposit_ratio_low": 0.40,
        "deposit_ratio_high": 0.66,
        "loan_ratio_low": 0.25,
        "loan_ratio_high": 0.52,
        "equity_ratio_low": 0.10,
        "equity_ratio_high": 0.19,
        "revenue_asset_low": 0.040,
        "revenue_asset_high": 0.078,
        "cost_income_low": 0.40,
        "cost_income_high": 0.64,
    },
    "CORPORATE_TREASURY_USD": {
        "asset_scale_low": 60.0e9,
        "asset_scale_high": 500.0e9,
        "deposit_ratio_low": 0.38,
        "deposit_ratio_high": 0.64,
        "loan_ratio_low": 0.24,
        "loan_ratio_high": 0.48,
        "equity_ratio_low": 0.07,
        "equity_ratio_high": 0.14,
        "revenue_asset_low": 0.025,
        "revenue_asset_high": 0.055,
        "cost_income_low": 0.38,
        "cost_income_high": 0.62,
    },
    "CORPORATE_INTERNATIONAL": {
        "asset_scale_low": 40.0e9,
        "asset_scale_high": 350.0e9,
        "deposit_ratio_low": 0.34,
        "deposit_ratio_high": 0.60,
        "loan_ratio_low": 0.25,
        "loan_ratio_high": 0.50,
        "equity_ratio_low": 0.07,
        "equity_ratio_high": 0.15,
        "revenue_asset_low": 0.025,
        "revenue_asset_high": 0.055,
        "cost_income_low": 0.40,
        "cost_income_high": 0.66,
    },
    "PRIVATE_WEALTH_INTERNATIONAL": {
        "asset_scale_low": 45.0e9,
        "asset_scale_high": 300.0e9,
        "deposit_ratio_low": 0.40,
        "deposit_ratio_high": 0.68,
        "loan_ratio_low": 0.18,
        "loan_ratio_high": 0.42,
        "equity_ratio_low": 0.08,
        "equity_ratio_high": 0.16,
        "revenue_asset_low": 0.030,
        "revenue_asset_high": 0.065,
        "cost_income_low": 0.38,
        "cost_income_high": 0.61,
    },
    "CROSS_BORDER_CORPORATE": {
        "asset_scale_low": 45.0e9,
        "asset_scale_high": 320.0e9,
        "deposit_ratio_low": 0.38,
        "deposit_ratio_high": 0.64,
        "loan_ratio_low": 0.23,
        "loan_ratio_high": 0.48,
        "equity_ratio_low": 0.07,
        "equity_ratio_high": 0.15,
        "revenue_asset_low": 0.027,
        "revenue_asset_high": 0.058,
        "cost_income_low": 0.40,
        "cost_income_high": 0.65,
    },
}


# =============================================================================
# UTILITY FUNCTIONS
# =============================================================================

def make_stream_rng(world_seed: int, stream_id: int) -> np.random.Generator:
    """Create a deterministic RNG stream inside the banks namespace."""
    return make_rng(
        world_seed=world_seed,
        namespace=RNG_NAMESPACE,
        stream=stream_id,
    )


def clip01(value: float) -> float:
    return float(np.clip(value, 0.0, 1.0))


def geometric_draw(
    rng: np.random.Generator,
    low: float,
    high: float,
) -> float:
    if low <= 0 or high <= 0 or low > high:
        raise ValueError("Invalid positive bounds for geometric draw.")
    return float(np.exp(rng.uniform(np.log(low), np.log(high))))


def softmax(values: np.ndarray) -> np.ndarray:
    values = np.asarray(values, dtype=float)
    shifted = values - np.max(values)
    exp_values = np.exp(shifted)
    return exp_values / exp_values.sum()


def allocate_bounded_residual(
    lower: np.ndarray,
    upper: np.ndarray,
    preferences: np.ndarray,
    target_sum: float = 1.0,
    tolerance: float = 1e-12,
    max_iter: int = 500,
) -> np.ndarray:
    """
    Allocate mass above lower bounds according to stochastic preferences while
    respecting every upper bound.

    The returned vector lies directly inside the feasible bounded simplex.
    """
    lower = np.asarray(lower, dtype=float)
    upper = np.asarray(upper, dtype=float)
    preferences = np.asarray(preferences, dtype=float)

    if not (lower.shape == upper.shape == preferences.shape):
        raise ValueError("Bounds and preferences must have identical shapes.")

    if np.any(lower > upper):
        raise ValueError("Lower bounds cannot exceed upper bounds.")

    if lower.sum() > target_sum + tolerance:
        raise ValueError("Lower bounds make the simplex infeasible.")

    if upper.sum() < target_sum - tolerance:
        raise ValueError("Upper bounds make the simplex infeasible.")

    if np.any(preferences < 0):
        raise ValueError("Preferences must be non-negative.")

    x = lower.copy()
    remaining = target_sum - float(x.sum())
    capacity = upper - lower
    active = capacity > tolerance

    iterations = 0

    while remaining > tolerance and np.any(active):
        iterations += 1

        if iterations > max_iter:
            raise RuntimeError("Bounded residual allocation did not converge.")

        active_idx = np.where(active)[0]
        active_preferences = preferences[active_idx].copy()

        if active_preferences.sum() <= 0:
            active_preferences = np.ones(len(active_idx), dtype=float)

        shares = active_preferences / active_preferences.sum()
        proposed = remaining * shares
        available = capacity[active_idx]

        accepted = np.minimum(proposed, available)
        x[active_idx] += accepted
        capacity[active_idx] -= accepted

        used = float(accepted.sum())
        remaining -= used
        active = capacity > tolerance

        if used <= tolerance:
            break

    residual = target_sum - float(x.sum())

    if abs(residual) > 1e-9:
        free = np.where(x < upper - 1e-10)[0]

        if free.size == 0:
            raise RuntimeError("Unable to close bounded simplex residual.")

        x[free[0]] += residual

    if np.any(x < lower - 1e-10) or np.any(x > upper + 1e-10):
        raise RuntimeError("Bounded allocation violated final constraints.")

    return x


def get_temporal_bank_name(
    bank_id: str,
    year: int,
    current_name: str,
) -> str:
    """Return the historically appropriate display name for a bank-year."""
    if bank_id == "B010":
        return "HSBC Uruguay" if year <= 2025 else "BTG Pactual Uruguay"

    return current_name


def get_bank_lookup(banks_df: pd.DataFrame) -> Dict[str, str]:
    return banks_df.set_index("bank_id")["bank_name"].to_dict()


# =============================================================================
# BANK DIMENSION
# =============================================================================

def build_banks_dataframe() -> pd.DataFrame:
    rows = [bank.__dict__ for bank in BANKS]
    df = pd.DataFrame(rows)

    expected_columns = [
        "bank_id",
        "bank_name",
        "bank_scope",
        "bank_type",
        "operating_country",
        "bank_profile",
        "usd_affinity",
        "business_affinity",
        "large_transfer_affinity",
        "bank_status",
    ]

    return df[expected_columns].copy()


# =============================================================================
# WORLD-LEVEL AFFINITIES AND FOREIGN SELECTION WEIGHTS
# =============================================================================

def generate_foreign_weights(
    banks_df: pd.DataFrame,
    rng: np.random.Generator,
) -> Tuple[Dict[str, float], float]:
    foreign = banks_df.loc[
        (banks_df["bank_scope"] == "FOREIGN")
        & (banks_df["bank_status"] == "ACTIVE")
    ].copy()

    alpha = float(
        rng.uniform(
            FOREIGN_DIRICHLET_ALPHA_LOW,
            FOREIGN_DIRICHLET_ALPHA_HIGH,
        )
    )

    weights = rng.dirichlet(np.full(len(foreign), alpha))

    return dict(zip(foreign["bank_id"], weights)), alpha


def generate_world_affinities(
    banks_df: pd.DataFrame,
    rng: np.random.Generator,
) -> Tuple[Dict[str, Dict[str, float]], float]:
    noise_sd = float(
        rng.uniform(
            AFFINITY_NOISE_SD_LOW,
            AFFINITY_NOISE_SD_HIGH,
        )
    )

    result: Dict[str, Dict[str, float]] = {}

    for row in banks_df.itertuples(index=False):
        if row.bank_scope == "BTYT":
            result[row.bank_id] = {
                "usd_affinity": float(row.usd_affinity),
                "business_affinity": float(row.business_affinity),
                "large_transfer_affinity": float(row.large_transfer_affinity),
            }
            continue

        result[row.bank_id] = {
            "usd_affinity": clip01(
                float(row.usd_affinity) + rng.normal(0.0, noise_sd)
            ),
            "business_affinity": clip01(
                float(row.business_affinity) + rng.normal(0.0, noise_sd)
            ),
            "large_transfer_affinity": clip01(
                float(row.large_transfer_affinity) + rng.normal(0.0, noise_sd)
            ),
        }

    return result, noise_sd


def build_world_parameters_dataframe(
    banks_df: pd.DataFrame,
    world_seed: int,
) -> pd.DataFrame:
    foreign_rng = make_stream_rng(world_seed, RNG_STREAM_FOREIGN)
    affinity_rng = make_stream_rng(world_seed, RNG_STREAM_AFFINITIES)
    market_param_rng = make_stream_rng(world_seed, RNG_STREAM_MARKET_PARAMS)

    foreign_weights, foreign_alpha = generate_foreign_weights(
        banks_df,
        foreign_rng,
    )

    affinities, affinity_noise_sd = generate_world_affinities(
        banks_df,
        affinity_rng,
    )

    persistence_by_bank: Dict[str, float] = {}
    innovation_sd_by_bank: Dict[str, float] = {}

    for bank_id in DOMESTIC_SYSTEM_IDS:
        params = MARKET_DYNAMICS[bank_id]

        persistence_by_bank[bank_id] = float(
            market_param_rng.uniform(
                params["persistence_low"],
                params["persistence_high"],
            )
        )

        innovation_sd_by_bank[bank_id] = float(
            market_param_rng.uniform(
                params["innovation_sd_low"],
                params["innovation_sd_high"],
            )
        )

    rows = []

    for row in banks_df.itertuples(index=False):
        is_foreign = row.bank_scope == "FOREIGN"
        is_domestic_system = row.bank_id in DOMESTIC_SYSTEM_IDS

        rows.append(
            {
                "world_seed": int(world_seed),
                "bank_id": row.bank_id,
                "bank_name": row.bank_name,
                "realized_usd_affinity": affinities[row.bank_id]["usd_affinity"],
                "realized_business_affinity": affinities[row.bank_id][
                    "business_affinity"
                ],
                "realized_large_transfer_affinity": affinities[row.bank_id][
                    "large_transfer_affinity"
                ],
                "foreign_selection_weight": (
                    foreign_weights[row.bank_id] if is_foreign else np.nan
                ),
                "foreign_dirichlet_alpha": (
                    foreign_alpha if is_foreign else np.nan
                ),
                "affinity_noise_sd": affinity_noise_sd,
                "market_persistence": (
                    persistence_by_bank[row.bank_id]
                    if is_domestic_system
                    else np.nan
                ),
                "market_innovation_sd": (
                    innovation_sd_by_bank[row.bank_id]
                    if is_domestic_system
                    else np.nan
                ),
            }
        )

    return pd.DataFrame(rows)


# =============================================================================
# 2021 DOMESTIC COMPETITIVE STATE
# =============================================================================

def generate_initial_market_weights(
    rng: np.random.Generator,
) -> Dict[str, float]:
    """
    Generate the 2021 domestic-system vector inside the explicit plausibility
    bands.

    BROU is required to be the largest institution in 2021. This anchors the
    historical starting hierarchy while preserving stochastic values for every
    bank.
    """
    ids = list(DOMESTIC_SYSTEM_IDS)

    lower = np.array(
        [INITIAL_MARKET_SPECS[bank_id]["low"] for bank_id in ids],
        dtype=float,
    )
    center = np.array(
        [INITIAL_MARKET_SPECS[bank_id]["center"] for bank_id in ids],
        dtype=float,
    )
    upper = np.array(
        [INITIAL_MARKET_SPECS[bank_id]["high"] for bank_id in ids],
        dtype=float,
    )

    if lower.sum() > 1.0 or upper.sum() < 1.0:
        raise ValueError("The 2021 market bands do not define a feasible simplex.")

    # Center the preference on the desired interior location above lower bounds.
    preferred_residual = np.clip(center - lower, 1e-8, None)
    preferred_residual /= preferred_residual.sum()

    for _ in range(INITIAL_MAX_ATTEMPTS):
        alpha = float(
            rng.uniform(
                INITIAL_DIRICHLET_ALPHA_LOW,
                INITIAL_DIRICHLET_ALPHA_HIGH,
            )
        )

        concentration = np.maximum(
            preferred_residual * alpha * len(ids),
            0.35,
        )

        preferences = rng.dirichlet(concentration)

        center_noise = rng.normal(
            0.0,
            INITIAL_CENTER_NOISE_SD,
            size=len(ids),
        )

        preferences = np.clip(preferences + center_noise, 1e-8, None)
        preferences /= preferences.sum()

        weights = allocate_bounded_residual(
            lower=lower,
            upper=upper,
            preferences=preferences,
            target_sum=1.0,
        )

        result = dict(zip(ids, weights))

        brou_weight = result["B001"]
        largest_other = max(
            value
            for bank_id, value in result.items()
            if bank_id != "B001"
        )

        if brou_weight > largest_other:
            return result

    raise RuntimeError(
        "Unable to generate a valid 2021 market state with BROU as leader."
    )


# =============================================================================
# SHARED MACRO ENVIRONMENT
# =============================================================================

def load_macro_environment(expected_world_seed: int) -> pd.DataFrame:
    """Load and validate the canonical world-level macro environment."""
    if not MACRO_INPUT.exists():
        raise FileNotFoundError(
            "Missing canonical macro environment. "
            f"Run the macro generator first: {MACRO_INPUT}"
        )

    macro_df = pd.read_csv(MACRO_INPUT)
    validate_macro_environment(macro_df)

    seeds = (
        pd.to_numeric(macro_df["world_seed"], errors="raise")
        .astype(int)
        .unique()
    )

    if len(seeds) != 1:
        raise ValueError(
            "Macro environment must contain exactly one world_seed."
        )

    if int(seeds[0]) != int(expected_world_seed):
        raise ValueError(
            "Macro environment world_seed does not match the banking "
            "world_seed."
        )

    return macro_df.sort_values("year").reset_index(drop=True)


# =============================================================================
# DOMESTIC TEMPORAL COMPETITIVE DYNAMICS
# =============================================================================

def calculate_macro_effect(
    bank_id: str,
    macro_row: pd.Series,
) -> float:
    params = MARKET_DYNAMICS[bank_id]

    return float(
        params["growth_beta"] * macro_row["macro_growth_factor"]
        + params["credit_beta"] * macro_row["credit_cycle_factor"]
        + params["usd_beta"] * macro_row["usd_pressure_factor"]
        + params["stress_beta"] * macro_row["financial_stress_factor"]
        + params["digital_beta"] * macro_row["digitalization_factor"]
        + params["cross_border_beta"] * macro_row["cross_border_factor"]
    )


def draw_bank_specific_shock(
    bank_id: str,
    rng: np.random.Generator,
) -> Tuple[float, bool]:
    params = MARKET_DYNAMICS[bank_id]

    # BROU keeps the ordinary shock channel but also receives a very rare,
    # materially larger downside event. This is the only special leadership
    # calibration in V4.0.1 and exists solely to make leadership change
    # possible rather than predetermined.
    if (
        bank_id == "B001"
        and rng.random() < BROU_SEVERE_SHOCK_PROBABILITY
    ):
        magnitude = float(
            rng.uniform(
                BROU_SEVERE_SHOCK_LOW,
                BROU_SEVERE_SHOCK_HIGH,
            )
        )
        return -magnitude, True

    is_shock = bool(rng.random() < params["shock_probability"])

    if not is_shock:
        return 0.0, False

    # Slight negative skew prevents a hidden optimism bias.
    sign = -1.0 if rng.random() < 0.53 else 1.0

    magnitude = float(
        rng.uniform(
            params["shock_scale_low"],
            params["shock_scale_high"],
        )
    )

    return sign * magnitude, True


def build_market_weights_dataframe(
    banks_df: pd.DataFrame,
    world_params_df: pd.DataFrame,
    macro_df: pd.DataFrame,
    world_seed: int,
) -> pd.DataFrame:
    initial_rng = make_stream_rng(world_seed, RNG_STREAM_2021_MARKET)
    dynamics_rng = make_stream_rng(world_seed, RNG_STREAM_MARKET_DYNAMICS)

    current_names = get_bank_lookup(banks_df)

    initial_weights = generate_initial_market_weights(initial_rng)

    center_values = np.array(
        [
            INITIAL_MARKET_SPECS[bank_id]["center"]
            for bank_id in DOMESTIC_SYSTEM_IDS
        ],
        dtype=float,
    )
    center_values /= center_values.sum()

    anchor_share = dict(zip(DOMESTIC_SYSTEM_IDS, center_values))
    anchor_latent = {
        bank_id: float(np.log(anchor_share[bank_id]))
        for bank_id in DOMESTIC_SYSTEM_IDS
    }

    market_params = (
        world_params_df.loc[
            world_params_df["bank_id"].isin(DOMESTIC_SYSTEM_IDS),
            [
                "bank_id",
                "market_persistence",
                "market_innovation_sd",
            ],
        ]
        .set_index("bank_id")
        .to_dict(orient="index")
    )

    rows = []
    previous_latent: Dict[str, float] = {}

    # Persistent strategic state is separate from ordinary AR persistence.
    # A material shock enters this state and then decays over subsequent years.
    strategic_state = {
        bank_id: 0.0
        for bank_id in DOMESTIC_SYSTEM_IDS
    }
    strategic_decay = {
        bank_id: float(
            dynamics_rng.uniform(
                STRATEGIC_SHOCK_DECAY_LOW,
                STRATEGIC_SHOCK_DECAY_HIGH,
            )
        )
        for bank_id in DOMESTIC_SYSTEM_IDS
    }

    # 2021 is generated directly from the bounded initialization contract.
    for bank_id in DOMESTIC_SYSTEM_IDS:
        weight = float(initial_weights[bank_id])
        latent = float(np.log(weight))

        previous_latent[bank_id] = latent

        rows.append(
            {
                "bank_id": bank_id,
                "bank_name": get_temporal_bank_name(
                    bank_id,
                    2021,
                    current_names[bank_id],
                ),
                "year": 2021,
                "market_weight": weight,
                "latent_competitive_state": latent,
                "long_run_anchor": anchor_share[bank_id],
                "persistence": market_params[bank_id]["market_persistence"],
                "macro_effect": 0.0,
                "systemic_shock_effect": 0.0,
                "bank_shock_effect": 0.0,
                "persistent_strategic_effect": 0.0,
                "idiosyncratic_innovation": 0.0,
                "is_bank_shock": False,
                "is_systemic_shock": False,
                "world_seed": int(world_seed),
            }
        )

    for year in YEARS[1:]:
        macro_row = macro_df.loc[macro_df["year"] == year].iloc[0]

        latent_by_bank: Dict[str, float] = {}
        components_by_bank: Dict[str, Dict[str, float | bool]] = {}

        for bank_id in DOMESTIC_SYSTEM_IDS:
            params = MARKET_DYNAMICS[bank_id]

            persistence = float(
                market_params[bank_id]["market_persistence"]
            )
            innovation_sd = float(
                market_params[bank_id]["market_innovation_sd"]
            )

            mu = anchor_latent[bank_id]
            previous = previous_latent[bank_id]

            macro_effect = calculate_macro_effect(bank_id, macro_row)

            systemic_effect = float(
                params["systemic_beta"]
                * macro_row["systemic_shock"]
            )

            bank_shock_effect, is_bank_shock = draw_bank_specific_shock(
                bank_id,
                dynamics_rng,
            )

            strategic_state[bank_id] = (
                strategic_decay[bank_id] * strategic_state[bank_id]
                + bank_shock_effect
            )
            persistent_strategic_effect = float(
                strategic_state[bank_id]
            )

            innovation = float(
                dynamics_rng.normal(0.0, innovation_sd)
            )

            latent = (
                mu
                + persistence * (previous - mu)
                + macro_effect
                + systemic_effect
                + persistent_strategic_effect
                + innovation
            )

            latent = float(
                np.clip(
                    latent,
                    mu - LATENT_DEVIATION_LIMIT,
                    mu + LATENT_DEVIATION_LIMIT,
                )
            )

            latent_by_bank[bank_id] = latent

            components_by_bank[bank_id] = {
                "macro_effect": macro_effect,
                "systemic_shock_effect": systemic_effect,
                "bank_shock_effect": bank_shock_effect,
                "persistent_strategic_effect": persistent_strategic_effect,
                "idiosyncratic_innovation": innovation,
                "is_bank_shock": is_bank_shock,
            }

        latent_vector = np.array(
            [latent_by_bank[bank_id] for bank_id in DOMESTIC_SYSTEM_IDS],
            dtype=float,
        )

        weights = softmax(latent_vector)
        weight_by_bank = dict(zip(DOMESTIC_SYSTEM_IDS, weights))

        for bank_id in DOMESTIC_SYSTEM_IDS:
            components = components_by_bank[bank_id]

            rows.append(
                {
                    "bank_id": bank_id,
                    "bank_name": get_temporal_bank_name(
                        bank_id,
                        year,
                        current_names[bank_id],
                    ),
                    "year": int(year),
                    "market_weight": float(weight_by_bank[bank_id]),
                    "latent_competitive_state": latent_by_bank[bank_id],
                    "long_run_anchor": anchor_share[bank_id],
                    "persistence": market_params[bank_id]["market_persistence"],
                    "macro_effect": components["macro_effect"],
                    "systemic_shock_effect": components[
                        "systemic_shock_effect"
                    ],
                    "bank_shock_effect": components["bank_shock_effect"],
                    "persistent_strategic_effect": components[
                        "persistent_strategic_effect"
                    ],
                    "idiosyncratic_innovation": components[
                        "idiosyncratic_innovation"
                    ],
                    "is_bank_shock": components["is_bank_shock"],
                    "is_systemic_shock": bool(
                        macro_row["systemic_shock_flag"]
                    ),
                    "world_seed": int(world_seed),
                }
            )

        previous_latent = latent_by_bank

    return pd.DataFrame(rows)


# =============================================================================
# FINANCIAL GENERATION
# =============================================================================

def get_financial_growth_baseline(
    bank_scope: str,
    rng: np.random.Generator,
) -> Tuple[float, float]:
    if bank_scope == "FOREIGN":
        return (
            float(rng.normal(0.045, 0.020)),
            float(rng.uniform(0.025, 0.060)),
        )

    if bank_scope == "DOMESTIC":
        return (
            float(rng.normal(0.035, 0.020)),
            float(rng.uniform(0.020, 0.050)),
        )

    return (
        float(rng.normal(0.055, 0.025)),
        float(rng.uniform(0.025, 0.060)),
    )


def build_market_history_lookup(
    market_df: pd.DataFrame,
) -> Dict[Tuple[str, int], dict]:
    lookup: Dict[Tuple[str, int], dict] = {}

    for row in market_df.itertuples(index=False):
        lookup[(row.bank_id, int(row.year))] = {
            "market_weight": float(row.market_weight),
            "bank_shock_effect": float(row.bank_shock_effect),
            "systemic_shock_effect": float(row.systemic_shock_effect),
        }

    return lookup


def generate_bank_financial_path(
    bank: BankDefinition,
    rng: np.random.Generator,
    macro_df: pd.DataFrame,
    market_lookup: Dict[Tuple[str, int], dict],
) -> Iterable[dict]:
    params = FINANCIAL_PROFILE_PARAMS[bank.bank_profile]

    assets = geometric_draw(
        rng,
        params["asset_scale_low"],
        params["asset_scale_high"],
    )

    deposit_ratio_anchor = float(
        rng.uniform(
            params["deposit_ratio_low"],
            params["deposit_ratio_high"],
        )
    )
    loan_ratio_anchor = float(
        rng.uniform(
            params["loan_ratio_low"],
            params["loan_ratio_high"],
        )
    )
    equity_ratio_anchor = float(
        rng.uniform(
            params["equity_ratio_low"],
            params["equity_ratio_high"],
        )
    )
    revenue_asset_anchor = float(
        rng.uniform(
            params["revenue_asset_low"],
            params["revenue_asset_high"],
        )
    )
    cost_income_anchor = float(
        rng.uniform(
            params["cost_income_low"],
            params["cost_income_high"],
        )
    )

    long_run_growth, growth_volatility = get_financial_growth_baseline(
        bank.bank_scope,
        rng,
    )

    previous_market_weight = None

    for year_index, year in enumerate(YEARS):
        macro_row = macro_df.loc[macro_df["year"] == year].iloc[0]

        market_info = market_lookup.get((bank.bank_id, year))

        if market_info is None:
            market_weight = np.nan
            market_delta = 0.0
            bank_shock = 0.0
            systemic_market_effect = 0.0
        else:
            market_weight = market_info["market_weight"]

            if previous_market_weight is None:
                market_delta = 0.0
            else:
                market_delta = market_weight - previous_market_weight

            bank_shock = market_info["bank_shock_effect"]
            systemic_market_effect = market_info[
                "systemic_shock_effect"
            ]

        if year_index > 0:
            macro_growth_effect = float(
                0.020 * macro_row["macro_growth_factor"]
                + 0.014 * macro_row["credit_cycle_factor"]
                - 0.016 * macro_row["financial_stress_factor"]
            )

            # Market-share changes are percentage-point changes. The coefficient
            # produces a moderate, not mechanical, link to asset growth.
            market_growth_effect = 1.10 * market_delta

            shock_growth_effect = (
                0.38 * bank_shock
                + 0.22 * systemic_market_effect
            )

            annual_growth = float(
                np.clip(
                    long_run_growth
                    + macro_growth_effect
                    + market_growth_effect
                    + shock_growth_effect
                    + rng.normal(0.0, growth_volatility),
                    -0.18,
                    0.25,
                )
            )

            assets *= 1.0 + annual_growth

        else:
            annual_growth = np.nan

        stress = float(macro_row["financial_stress_factor"])
        credit_cycle = float(macro_row["credit_cycle_factor"])

        deposit_ratio = float(
            np.clip(
                deposit_ratio_anchor
                + rng.normal(0.0, 0.022)
                + 0.008 * macro_row["macro_growth_factor"]
                - 0.006 * stress,
                params["deposit_ratio_low"],
                params["deposit_ratio_high"],
            )
        )

        loan_ratio = float(
            np.clip(
                loan_ratio_anchor
                + rng.normal(0.0, 0.022)
                + 0.010 * credit_cycle
                - 0.008 * stress,
                params["loan_ratio_low"],
                params["loan_ratio_high"],
            )
        )

        equity_ratio = float(
            np.clip(
                equity_ratio_anchor
                + rng.normal(0.0, 0.010)
                - 0.004 * max(stress, 0.0),
                params["equity_ratio_low"],
                params["equity_ratio_high"],
            )
        )

        revenue_asset_ratio = float(
            np.clip(
                revenue_asset_anchor
                + rng.normal(0.0, 0.004)
                + 0.002 * macro_row["macro_growth_factor"]
                + 0.001 * macro_row["usd_pressure_factor"],
                params["revenue_asset_low"],
                params["revenue_asset_high"],
            )
        )

        cost_income_ratio = float(
            np.clip(
                cost_income_anchor
                + rng.normal(0.0, 0.025)
                + 0.008 * max(stress, 0.0)
                - 0.004 * macro_row["digitalization_factor"],
                params["cost_income_low"],
                params["cost_income_high"],
            )
        )

        total_deposits = assets * deposit_ratio
        total_loans = assets * loan_ratio
        equity = assets * equity_ratio
        revenue = assets * revenue_asset_ratio
        operating_costs = revenue * cost_income_ratio

        charge_ratio = float(
            np.clip(
                rng.normal(0.16, 0.055)
                + 0.018 * max(stress, 0.0)
                - 0.006 * min(credit_cycle, 0.0),
                0.03,
                0.38,
            )
        )

        additional_net_charges = revenue * charge_ratio

        net_income = (
            revenue
            - operating_costs
            - additional_net_charges
        )

        loss_probability = float(
            np.clip(
                LOSS_YEAR_BASE_PROBABILITY
                + 0.030 * max(stress, 0.0),
                0.0,
                0.18,
            )
        )

        if rng.random() < loss_probability:
            stress_charge = revenue * rng.uniform(0.15, 0.55)
            net_income -= stress_charge

        yield {
            "bank_id": bank.bank_id,
            "bank_name": get_temporal_bank_name(
                bank.bank_id,
                year,
                bank.bank_name,
            ),
            "year": int(year),
            "revenue": round(float(revenue), 2),
            "operating_costs": round(float(operating_costs), 2),
            "net_income": round(float(net_income), 2),
            "total_assets": round(float(assets), 2),
            "total_deposits": round(float(total_deposits), 2),
            "total_loans": round(float(total_loans), 2),
            "equity": round(float(equity), 2),
            "reporting_currency": REPORTING_CURRENCY,
        }

        if market_info is not None:
            previous_market_weight = market_weight


def build_bank_financials_dataframe(
    macro_df: pd.DataFrame,
    market_df: pd.DataFrame,
    world_seed: int,
) -> pd.DataFrame:
    rng = make_stream_rng(world_seed, RNG_STREAM_FINANCIALS)
    market_lookup = build_market_history_lookup(market_df)

    rows = []

    for bank in BANKS:
        rows.extend(
            generate_bank_financial_path(
                bank=bank,
                rng=rng,
                macro_df=macro_df,
                market_lookup=market_lookup,
            )
        )

    return pd.DataFrame(rows)


# =============================================================================
# VALIDATION
# =============================================================================

def validate_banks(banks_df: pd.DataFrame) -> None:
    if banks_df["bank_id"].duplicated().any():
        raise ValueError("Duplicate bank_id detected.")

    if banks_df["bank_name"].duplicated().any():
        raise ValueError("Duplicate current-state bank_name detected.")

    allowed_scopes = {"BTYT", "DOMESTIC", "FOREIGN"}

    if not set(banks_df["bank_scope"]).issubset(allowed_scopes):
        raise ValueError("Invalid bank_scope detected.")

    affinity_columns = [
        "usd_affinity",
        "business_affinity",
        "large_transfer_affinity",
    ]

    for column in affinity_columns:
        if not banks_df[column].between(0.0, 1.0).all():
            raise ValueError(f"{column} must be between 0 and 1.")

    b010 = banks_df.loc[banks_df["bank_id"] == "B010"]

    if len(b010) != 1:
        raise ValueError("B010 must exist exactly once.")

    if b010.iloc[0]["bank_name"] != "BTG Pactual Uruguay":
        raise ValueError(
            "B010 current-state name must be BTG Pactual Uruguay."
        )

    missing_market_configs = (
        set(DOMESTIC_SYSTEM_IDS)
        - set(INITIAL_MARKET_SPECS)
    )

    if missing_market_configs:
        raise ValueError(
            f"Missing initial market specs: {sorted(missing_market_configs)}"
        )

    missing_dynamic_configs = (
        set(DOMESTIC_SYSTEM_IDS)
        - set(MARKET_DYNAMICS)
    )

    if missing_dynamic_configs:
        raise ValueError(
            f"Missing market dynamics: {sorted(missing_dynamic_configs)}"
        )


def validate_world_parameters(
    banks_df: pd.DataFrame,
    world_df: pd.DataFrame,
) -> None:
    if world_df["bank_id"].duplicated().any():
        raise ValueError("Duplicate bank_id in bank_world_parameters.csv.")

    expected_ids = set(banks_df["bank_id"])

    if set(world_df["bank_id"]) != expected_ids:
        raise ValueError(
            "World-parameter bank IDs do not match banks.csv."
        )

    expected_names = banks_df.set_index("bank_id")["bank_name"].to_dict()

    mismatched_names = world_df[
        world_df.apply(
            lambda row: expected_names[row["bank_id"]] != row["bank_name"],
            axis=1,
        )
    ]

    if not mismatched_names.empty:
        raise ValueError(
            "bank_name does not match bank_id in world parameters."
        )

    affinity_columns = [
        "realized_usd_affinity",
        "realized_business_affinity",
        "realized_large_transfer_affinity",
    ]

    for column in affinity_columns:
        if not world_df[column].between(0.0, 1.0).all():
            raise ValueError(f"{column} must be between 0 and 1.")

    merged = world_df.merge(
        banks_df[["bank_id", "bank_scope"]],
        on="bank_id",
        how="left",
        validate="one_to_one",
    )

    foreign = merged.loc[merged["bank_scope"] == "FOREIGN"].copy()
    non_foreign = merged.loc[merged["bank_scope"] != "FOREIGN"].copy()

    if not np.isclose(
        foreign["foreign_selection_weight"].sum(),
        1.0,
        atol=1e-10,
    ):
        raise ValueError("Foreign selection weights do not sum to 1.")

    if (foreign["foreign_selection_weight"] <= 0).any():
        raise ValueError("Foreign selection weights must be positive.")

    if non_foreign["foreign_selection_weight"].notna().any():
        raise ValueError(
            "Only foreign banks may have foreign_selection_weight."
        )

    domestic_system = world_df.loc[
        world_df["bank_id"].isin(DOMESTIC_SYSTEM_IDS)
    ]

    if domestic_system["market_persistence"].isna().any():
        raise ValueError(
            "Domestic-system banks require market_persistence."
        )

    if not domestic_system["market_persistence"].between(
        0.0,
        1.0,
        inclusive="neither",
    ).all():
        raise ValueError("Market persistence must lie inside (0,1).")

    if (domestic_system["market_innovation_sd"] <= 0).any():
        raise ValueError("Market innovation SD must be positive.")



def validate_market_weights(
    banks_df: pd.DataFrame,
    market_df: pd.DataFrame,
) -> None:
    expected_rows = len(DOMESTIC_SYSTEM_IDS) * len(YEARS)

    if len(market_df) != expected_rows:
        raise ValueError(
            f"Expected {expected_rows} market rows, found {len(market_df)}."
        )

    if market_df.duplicated(["bank_id", "year"]).any():
        raise ValueError("Duplicate (bank_id, year) in market weights.")

    if set(market_df["bank_id"]) != set(DOMESTIC_SYSTEM_IDS):
        raise ValueError("Unexpected bank IDs in domestic market table.")

    if set(market_df["year"]) != set(YEARS):
        raise ValueError("Domestic market table has incorrect year coverage.")

    if (market_df["market_weight"] <= 0).any():
        raise ValueError("Domestic market weights must be positive.")

    annual_sums = market_df.groupby("year")["market_weight"].sum()

    if not np.allclose(
        annual_sums.to_numpy(),
        np.ones(len(annual_sums)),
        atol=1e-10,
    ):
        raise ValueError("Annual domestic market weights do not sum to 1.")

    annual_max = market_df.groupby("year")["market_weight"].max()

    if (annual_max > MAX_DOMESTIC_WEIGHT_GUARDRAIL).any():
        raise ValueError(
            "A domestic market weight exceeded the configured guardrail."
        )

    current_names = get_bank_lookup(banks_df)

    mismatched_names = market_df[
        market_df.apply(
            lambda row: get_temporal_bank_name(
                row["bank_id"],
                int(row["year"]),
                current_names[row["bank_id"]],
            )
            != row["bank_name"],
            axis=1,
        )
    ]

    if not mismatched_names.empty:
        raise ValueError(
            "Temporal bank_name mismatch in market weights."
        )

    initial = (
        market_df.loc[market_df["year"] == 2021]
        .set_index("bank_id")
    )

    for bank_id in DOMESTIC_SYSTEM_IDS:
        value = float(initial.loc[bank_id, "market_weight"])
        low = INITIAL_MARKET_SPECS[bank_id]["low"]
        high = INITIAL_MARKET_SPECS[bank_id]["high"]

        if value < low - 1e-10 or value > high + 1e-10:
            raise ValueError(
                f"2021 weight for {bank_id} falls outside its band."
            )

    leader_2021 = initial["market_weight"].idxmax()

    if leader_2021 != "B001":
        raise ValueError("BROU must be the 2021 market leader.")

    btyt_2021 = float(initial.loc["B000", "market_weight"])

    if not (
        INITIAL_MARKET_SPECS["B000"]["low"]
        <= btyt_2021
        <= INITIAL_MARKET_SPECS["B000"]["high"]
    ):
        raise ValueError("BTYT 2021 weight is outside its design band.")

    if not market_df["persistence"].between(
        0.0,
        1.0,
        inclusive="neither",
    ).all():
        raise ValueError("Invalid persistence in market table.")

    if market_df[
        [
            "latent_competitive_state",
            "long_run_anchor",
            "macro_effect",
            "systemic_shock_effect",
            "bank_shock_effect",
            "persistent_strategic_effect",
            "idiosyncratic_innovation",
        ]
    ].isna().any().any():
        raise ValueError("Missing market-dynamics components detected.")

    shock_consistency = (
        market_df["is_bank_shock"]
        == (market_df["bank_shock_effect"] != 0.0)
    )

    if not shock_consistency.all():
        raise ValueError("Bank-shock flag/value mismatch.")


def validate_financials(
    banks_df: pd.DataFrame,
    financials_df: pd.DataFrame,
) -> None:
    if financials_df.duplicated(["bank_id", "year"]).any():
        raise ValueError("Duplicate (bank_id, year) in bank financials.")

    known_ids = set(banks_df["bank_id"])

    if set(financials_df["bank_id"]) != known_ids:
        raise ValueError(
            "Financial bank IDs do not match banks.csv."
        )

    expected_rows = len(banks_df) * len(YEARS)

    if len(financials_df) != expected_rows:
        raise ValueError(
            f"Expected {expected_rows} financial rows, "
            f"found {len(financials_df)}."
        )

    coverage = financials_df.groupby("bank_id")["year"].apply(set)

    if not all(years == set(YEARS) for years in coverage):
        raise ValueError("Incomplete financial year coverage.")

    current_names = get_bank_lookup(banks_df)

    mismatched_names = financials_df[
        financials_df.apply(
            lambda row: get_temporal_bank_name(
                row["bank_id"],
                int(row["year"]),
                current_names[row["bank_id"]],
            )
            != row["bank_name"],
            axis=1,
        )
    ]

    if not mismatched_names.empty:
        raise ValueError(
            "Temporal bank_name mismatch in financials."
        )

    positive_columns = [
        "revenue",
        "operating_costs",
        "total_assets",
        "total_deposits",
        "total_loans",
        "equity",
    ]

    for column in positive_columns:
        if (financials_df[column] <= 0).any():
            raise ValueError(f"{column} must be positive.")

    if (
        financials_df["total_loans"]
        >= financials_df["total_assets"]
    ).any():
        raise ValueError("total_loans must remain below total_assets.")

    if (
        financials_df["total_deposits"]
        >= financials_df["total_assets"]
    ).any():
        raise ValueError("total_deposits must remain below total_assets.")

    if (
        financials_df["equity"]
        >= financials_df["total_assets"]
    ).any():
        raise ValueError("equity must remain below total_assets.")

    if financials_df["net_income"].isna().any():
        raise ValueError("Missing net_income detected.")

    if set(financials_df["reporting_currency"]) != {REPORTING_CURRENCY}:
        raise ValueError("Unexpected reporting currency.")


# =============================================================================
# CROSS-WORLD DOMESTIC MARKET AUDIT
# =============================================================================

def run_market_audit(
    banks_df: pd.DataFrame,
    n_worlds: int,
    audit_seed: int,
) -> pd.DataFrame:
    """
    Audit only the competitive engine.

    Financial generation is deliberately excluded so a 10,000-world audit can
    remain lightweight enough for development use.
    """
    if n_worlds <= 0:
        raise ValueError("n_worlds must be positive.")

    names = get_bank_lookup(banks_df)

    records = []
    leader_change_count = 0
    btyt_gain_count = 0
    systemic_year_count = 0
    bank_shock_count = 0

    for world_index in range(n_worlds):
        world_seed = int(audit_seed + world_index)

        world_df = build_world_parameters_dataframe(
            banks_df,
            world_seed,
        )
        macro_df = build_macro_environment_dataframe(world_seed)
        market_df = build_market_weights_dataframe(
            banks_df=banks_df,
            world_params_df=world_df,
            macro_df=macro_df,
            world_seed=world_seed,
        )

        weights_2021 = (
            market_df.loc[market_df["year"] == 2021]
            .set_index("bank_id")["market_weight"]
        )
        weights_2026 = (
            market_df.loc[market_df["year"] == 2026]
            .set_index("bank_id")["market_weight"]
        )

        ranks_2021 = weights_2021.rank(
            ascending=False,
            method="min",
        )
        ranks_2026 = weights_2026.rank(
            ascending=False,
            method="min",
        )

        leader_2021 = weights_2021.idxmax()
        leader_2026 = weights_2026.idxmax()

        if leader_2021 != leader_2026:
            leader_change_count += 1

        if weights_2026["B000"] > weights_2021["B000"]:
            btyt_gain_count += 1

        systemic_year_count += int(
            macro_df["systemic_shock_flag"].sum()
        )
        bank_shock_count += int(
            market_df["is_bank_shock"].sum()
        )

        for bank_id in DOMESTIC_SYSTEM_IDS:
            records.append(
                {
                    "world_seed": world_seed,
                    "bank_id": bank_id,
                    "weight_2021": float(weights_2021[bank_id]),
                    "weight_2026": float(weights_2026[bank_id]),
                    "change_2021_2026": float(
                        weights_2026[bank_id]
                        - weights_2021[bank_id]
                    ),
                    "rank_2021": int(ranks_2021[bank_id]),
                    "rank_2026": int(ranks_2026[bank_id]),
                    "leader_2021": bank_id == leader_2021,
                    "leader_2026": bank_id == leader_2026,
                    "top3_2021": ranks_2021[bank_id] <= 3,
                    "top3_2026": ranks_2026[bank_id] <= 3,
                }
            )

    detail = pd.DataFrame(records)

    rows = []

    for bank_id in DOMESTIC_SYSTEM_IDS:
        bank = detail.loc[detail["bank_id"] == bank_id]

        rows.append(
            {
                "bank_id": bank_id,
                "bank_name": names[bank_id],
                "mean_2021": bank["weight_2021"].mean(),
                "median_2021": bank["weight_2021"].median(),
                "p05_2021": bank["weight_2021"].quantile(0.05),
                "p95_2021": bank["weight_2021"].quantile(0.95),
                "leader_pct_2021": bank["leader_2021"].mean(),
                "top3_pct_2021": bank["top3_2021"].mean(),
                "mean_2026": bank["weight_2026"].mean(),
                "median_2026": bank["weight_2026"].median(),
                "p05_2026": bank["weight_2026"].quantile(0.05),
                "p95_2026": bank["weight_2026"].quantile(0.95),
                "leader_pct_2026": bank["leader_2026"].mean(),
                "top3_pct_2026": bank["top3_2026"].mean(),
                "mean_change_2021_2026": bank[
                    "change_2021_2026"
                ].mean(),
                "gain_pct_2021_2026": (
                    bank["change_2021_2026"] > 0
                ).mean(),
            }
        )

    summary = pd.DataFrame(rows).sort_values(
        "mean_2021",
        ascending=False,
    )

    print("\n" + "=" * 92)
    print("BTYT V4 DOMESTIC MARKET AUDIT")
    print("=" * 92)
    print(f"Worlds simulated: {n_worlds:,}")
    print(f"Audit seed: {audit_seed}")
    print(f"2021 market RNG stream: {RNG_STREAM_2021_MARKET}")
    print(f"Market dynamics RNG stream: {RNG_STREAM_MARKET_DYNAMICS}")
    print()

    print(
        f"{'Bank':<28}"
        f"{'2021 Mean':>11}"
        f"{'2021 P05':>10}"
        f"{'2021 P95':>10}"
        f"{'2026 Mean':>11}"
        f"{'2026 P05':>10}"
        f"{'2026 P95':>10}"
        f"{'Gain %':>9}"
    )

    for row in summary.itertuples(index=False):
        print(
            f"{row.bank_name:<28}"
            f"{row.mean_2021:>10.2%}"
            f"{row.p05_2021:>10.2%}"
            f"{row.p95_2021:>10.2%}"
            f"{row.mean_2026:>11.2%}"
            f"{row.p05_2026:>10.2%}"
            f"{row.p95_2026:>10.2%}"
            f"{row.gain_pct_2021_2026:>9.2%}"
        )

    print()
    print(
        f"Leadership changed by 2026: "
        f"{leader_change_count / n_worlds:.2%}"
    )
    print(
        f"BTYT gained weight by 2026: "
        f"{btyt_gain_count / n_worlds:.2%}"
    )
    print(
        f"Average systemic-shock years per world: "
        f"{systemic_year_count / n_worlds:.3f}"
    )
    print(
        f"Average bank-specific shocks per world: "
        f"{bank_shock_count / n_worlds:.3f}"
    )

    return summary


# =============================================================================
# REPORTING
# =============================================================================

def print_world_summary(
    banks_df: pd.DataFrame,
    world_df: pd.DataFrame,
    macro_df: pd.DataFrame,
    market_df: pd.DataFrame,
    financials_df: pd.DataFrame,
    world_seed: int,
    saved: bool,
) -> None:
    print("=" * 84)
    print("BTYT BANK NETWORK GENERATOR — V4.0.1")
    print("=" * 84)
    print(f"WORLD_SEED: {world_seed}")
    print(f"RNG_NAMESPACE: {RNG_NAMESPACE}")
    print(
        "RNG streams: "
        f"2021_market={RNG_STREAM_2021_MARKET}, "
        f"foreign={RNG_STREAM_FOREIGN}, "
        f"affinities={RNG_STREAM_AFFINITIES}, "
        f"financials={RNG_STREAM_FINANCIALS}, "
        f"market_params={RNG_STREAM_MARKET_PARAMS}, "
        "macro=upstream_world_generator, "
        f"market_dynamics={RNG_STREAM_MARKET_DYNAMICS}"
    )
    print(f"Banks: {len(banks_df)}")
    print(f"Market rows: {len(market_df)}")
    print(f"Macro rows: {len(macro_df)}")
    print(f"Financial rows: {len(financials_df)}")
    print(
        "B010 temporal identity: "
        "HSBC Uruguay (2021-2025) -> BTG Pactual Uruguay (2026)"
    )

    print("\nDomestic competitive weights:")

    pivot = market_df.pivot(
        index="bank_id",
        columns="year",
        values="market_weight",
    )

    # Sorting by 2021 produces a stable human-readable summary while bank_id
    # prevents B010 from being split into two rows by its temporal name change.
    pivot = pivot.sort_values(2021, ascending=False)
    current_names = get_bank_lookup(banks_df)

    for bank_id, row in pivot.iterrows():
        if bank_id == "B010":
            display_name = "HSBC / BTG Pactual Uruguay"
        else:
            display_name = current_names[bank_id]

        values = "  ".join(
            f"{year}: {row[year]:6.2%}"
            for year in YEARS
        )
        print(f"  {display_name:<28} {values}")

    btyt = market_df.loc[market_df["bank_id"] == "B000"].sort_values("year")
    btyt_change = (
        btyt.iloc[-1]["market_weight"]
        - btyt.iloc[0]["market_weight"]
    )

    print(
        f"\nBTYT 2021 -> 2026 competitive change: "
        f"{btyt_change:+.2%}"
    )

    systemic_years = macro_df.loc[
        macro_df["systemic_shock_flag"],
        "year",
    ].tolist()

    print(
        "Systemic-shock years: "
        + (
            ", ".join(map(str, systemic_years))
            if systemic_years
            else "none"
        )
    )

    print(
        f"Bank-specific shock events: "
        f"{int(market_df['is_bank_shock'].sum())}"
    )

    foreign = (
        world_df.loc[
            world_df["foreign_selection_weight"].notna(),
            ["bank_name", "foreign_selection_weight"],
        ]
        .sort_values("foreign_selection_weight", ascending=False)
    )

    print("\nForeign counterparty selection weights:")

    for row in foreign.itertuples(index=False):
        print(
            f"  {row.bank_name:<32} "
            f"{row.foreign_selection_weight:>7.2%}"
        )

    latest_financials = financials_df.loc[
        financials_df["year"] == FINANCIAL_END_YEAR
    ].sort_values("total_assets", ascending=False)

    print("\nLargest 2026 synthetic institutions by assets:")

    for row in latest_financials.head(7).itertuples(index=False):
        print(
            f"  {row.bank_name:<32} "
            f"${row.total_assets / 1e9:>10.2f}B"
        )

    print("\nVALIDATION: PASS")

    if saved:
        print(f"\nSaved: {BANKS_OUTPUT}")
        print(f"Saved: {WORLD_PARAMS_OUTPUT}")
        print(f"Consumed: {MACRO_INPUT}")
        print(f"Saved: {MARKET_OUTPUT}")
        print(f"Saved: {FINANCIALS_OUTPUT}")
    else:
        print("\nNo files written (--no-save).")


# =============================================================================
# PRODUCTION WORLD
# =============================================================================

def generate_production_world(
    world_seed: int,
    save: bool = True,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    banks_df = build_banks_dataframe()
    validate_banks(banks_df)

    world_df = build_world_parameters_dataframe(
        banks_df=banks_df,
        world_seed=world_seed,
    )
    validate_world_parameters(banks_df, world_df)

    macro_df = load_macro_environment(
        expected_world_seed=world_seed,
    )

    market_df = build_market_weights_dataframe(
        banks_df=banks_df,
        world_params_df=world_df,
        macro_df=macro_df,
        world_seed=world_seed,
    )
    validate_market_weights(
        banks_df=banks_df,
        market_df=market_df,
    )

    financials_df = build_bank_financials_dataframe(
        macro_df=macro_df,
        market_df=market_df,
        world_seed=world_seed,
    )
    validate_financials(
        banks_df=banks_df,
        financials_df=financials_df,
    )

    if save:
        BANKS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        WORLD_PARAMS_OUTPUT.parent.mkdir(parents=True, exist_ok=True)

        banks_df.to_csv(BANKS_OUTPUT, index=False)
        world_df.to_csv(WORLD_PARAMS_OUTPUT, index=False)
        market_df.to_csv(MARKET_OUTPUT, index=False)
        financials_df.to_csv(FINANCIALS_OUTPUT, index=False)

    return (
        banks_df,
        world_df,
        macro_df,
        market_df,
        financials_df,
    )


# =============================================================================
# CLI
# =============================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate the BTYT V4.0.1 synthetic banking system."
    )

    parser.add_argument(
        "--world-seed",
        type=int,
        default=WORLD_SEED,
        help=f"Production world seed. Default: {WORLD_SEED}",
    )

    parser.add_argument(
        "--audit-worlds",
        type=int,
        default=0,
        help=(
            "Run the lightweight domestic market audit across N worlds. "
            "Use 10000 for the full design audit."
        ),
    )

    parser.add_argument(
        "--audit-seed",
        type=int,
        default=20260901,
        help="Starting seed used by the cross-world market audit.",
    )

    parser.add_argument(
        "--no-save",
        action="store_true",
        help="Generate and validate without writing production CSV files.",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    (
        banks_df,
        world_df,
        macro_df,
        market_df,
        financials_df,
    ) = generate_production_world(
        world_seed=args.world_seed,
        save=not args.no_save,
    )

    print_world_summary(
        banks_df=banks_df,
        world_df=world_df,
        macro_df=macro_df,
        market_df=market_df,
        financials_df=financials_df,
        world_seed=args.world_seed,
        saved=not args.no_save,
    )

    if args.audit_worlds > 0:
        audit_df = run_market_audit(
            banks_df=banks_df,
            n_worlds=args.audit_worlds,
            audit_seed=args.audit_seed,
        )

        if not args.no_save:
            AUDIT_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
            audit_df.to_csv(AUDIT_OUTPUT, index=False)
            print(f"\nSaved audit: {AUDIT_OUTPUT}")


if __name__ == "__main__":
    main()
