from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]

CONFIG_DIR = PROJECT_ROOT / "config"
DATA_DIR = PROJECT_ROOT / "data"

# Generated data
GENERATED_DATA_DIR = DATA_DIR / "generated"
GENERATED_WORLD_DIR = GENERATED_DATA_DIR / "world"
GENERATED_CORE_DIR = GENERATED_DATA_DIR / "core"
GENERATED_CREDIT_DIR = GENERATED_DATA_DIR / "credit"
GENERATED_TRANSACTIONS_DIR = GENERATED_DATA_DIR / "transactions"
GENERATED_CAMPAIGNS_DIR = GENERATED_DATA_DIR / "campaigns"
GENERATED_PERFORMANCE_DIR = GENERATED_DATA_DIR / "performance"

# Interim data
INTERIM_DATA_DIR = DATA_DIR / "interim"
INTERIM_WORLD_DIR = INTERIM_DATA_DIR / "world"
INTERIM_TRANSACTIONS_DIR = INTERIM_DATA_DIR / "transactions"
INTERIM_CREDIT_DIR = INTERIM_DATA_DIR / "credit"
INTERIM_AUDITS_DIR = INTERIM_DATA_DIR / "audits"

# Operational data
OPERATIONAL_DATA_DIR = DATA_DIR / "operational"
OPERATIONAL_CORE_DIR = OPERATIONAL_DATA_DIR / "core"
OPERATIONAL_TRANSACTIONS_DIR = OPERATIONAL_DATA_DIR / "transactions"
OPERATIONAL_CREDIT_DIR = OPERATIONAL_DATA_DIR / "credit"
OPERATIONAL_CAMPAIGNS_DIR = OPERATIONAL_DATA_DIR / "campaigns"

# Database
DATABASE_DIR = PROJECT_ROOT / "database"

# Configuration files
WORLD_CONFIG_PATH = CONFIG_DIR / "world_config.json"