#!/usr/bin/env python
"""
BTYT Campaign Behavioral Layer — Monte Carlo Audit V1.0.0

Purpose
-------
Audit the distributional plausibility and stability of the frozen candidate
Campaign Behavioral Engine V1.0.2 without regenerating observable banking data.

This audit is deliberately lightweight. It does not rerun the full customer-level
campaign engine in every world. Instead it:

1. Reads the production Phase A outputs generated by V1.0.2.
2. Reconstructs campaign-level production counts and response composition.
3. Uses a hierarchical Beta-Binomial / Dirichlet-Multinomial Monte Carlo layer
   to stress selection, exposure, response, and response composition.
4. Preserves small-campaign uncertainty instead of forcing smooth percentages.
5. Audits production customer overlap, exposure concentration, fatigue proxies,
   and channel mix directly from the generated tables.
6. Applies broad structural/plausibility guardrails rather than target rates.

Important
---------
This is an audit of the realized campaign behavioral layer, not a replacement
generator and not a downstream conversion model.

No production table is modified.

Expected production inputs
--------------------------
data/generated/campaign_customers.csv
data/generated/campaign_exposures.csv
data/interim/campaign_generation_audit.csv
data/master/campaigns.csv
data/master/campaign_channels.csv

Outputs
-------
data/interim/campaign_monte_carlo_world_summary.csv
data/interim/campaign_monte_carlo_campaign_summary.csv
data/interim/campaign_monte_carlo_guardrails.csv
data/interim/campaign_production_behavior_diagnostics.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


# =============================================================================
# Configuration
# =============================================================================

ENGINE_VERSION = "1.0.0"
DEFAULT_AUDIT_SEED = 20260902
DEFAULT_WORLDS = 10_000

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_MASTER = PROJECT_ROOT / "data" / "master"
DATA_GENERATED = PROJECT_ROOT / "data" / "generated"
DATA_INTERIM = PROJECT_ROOT / "data" / "interim"

CAMPAIGNS_PATH = DATA_MASTER / "campaigns.csv"
CAMPAIGN_CHANNELS_PATH = DATA_MASTER / "campaign_channels.csv"
CAMPAIGN_CUSTOMERS_PATH = DATA_GENERATED / "campaign_customers.csv"
CAMPAIGN_EXPOSURES_PATH = DATA_GENERATED / "campaign_exposures.csv"
CAMPAIGN_AUDIT_PATH = DATA_INTERIM / "campaign_generation_audit.csv"

WORLD_SUMMARY_PATH = DATA_INTERIM / "campaign_monte_carlo_world_summary.csv"
CAMPAIGN_SUMMARY_PATH = DATA_INTERIM / "campaign_monte_carlo_campaign_summary.csv"
GUARDRAILS_PATH = DATA_INTERIM / "campaign_monte_carlo_guardrails.csv"
PRODUCTION_DIAGNOSTICS_PATH = (
    DATA_INTERIM / "campaign_production_behavior_diagnostics.csv"
)

RNG_STREAMS = {
    "selection_probability": 810,
    "selection_realization": 811,
    "exposure_probability": 820,
    "exposure_realization": 821,
    "response_probability": 830,
    "response_realization": 831,
    "response_mix": 840,
    "response_mix_realization": 841,
    "followup_intensity": 850,
    "followup_realization": 851,
}

# Broad prior concentrations. These are intentionally moderate:
# large campaigns remain relatively stable while small campaigns retain
# substantial stochastic uncertainty.
SELECTION_CONCENTRATION = 90.0
EXPOSURE_CONCENTRATION = 110.0
RESPONSE_CONCENTRATION = 75.0
RESPONSE_MIX_CONCENTRATION = 55.0
FOLLOWUP_CONCENTRATION = 70.0

EPS = 1e-6


# =============================================================================
# Generic helpers
# =============================================================================

def make_rng(seed: int, stream: int) -> np.random.Generator:
    ss = np.random.SeedSequence([int(seed), int(stream)])
    return np.random.default_rng(ss)


def read_csv_required(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Required file not found: {path}")
    df = pd.read_csv(path)
    unnamed = [c for c in df.columns if str(c).lower().startswith("unnamed")]
    if unnamed:
        df = df.drop(columns=unnamed)
    if "index" in df.columns:
        df = df.drop(columns=["index"])
    return df


def ensure_columns(df: pd.DataFrame, required: Iterable[str], name: str) -> None:
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{name} is missing required columns: {missing}")


def pct(x: float) -> str:
    return f"{100.0 * x:6.2f}%"


def q(series: np.ndarray, p: float) -> float:
    return float(np.quantile(series, p))


def beta_shapes(mean: float, concentration: float) -> tuple[float, float]:
    mean = float(np.clip(mean, EPS, 1.0 - EPS))
    return mean * concentration, (1.0 - mean) * concentration


def safe_rate(num: np.ndarray, den: np.ndarray) -> np.ndarray:
    out = np.zeros_like(num, dtype=float)
    mask = den > 0
    out[mask] = num[mask] / den[mask]
    return out


def weighted_mean(values: np.ndarray, weights: np.ndarray) -> float:
    total = float(weights.sum())
    if total <= 0:
        return 0.0
    return float(np.sum(values * weights) / total)


# =============================================================================
# Production loading and reconstruction
# =============================================================================

def load_inputs():
    campaigns = read_csv_required(CAMPAIGNS_PATH)
    channels = read_csv_required(CAMPAIGN_CHANNELS_PATH)
    campaign_customers = read_csv_required(CAMPAIGN_CUSTOMERS_PATH)
    exposures = read_csv_required(CAMPAIGN_EXPOSURES_PATH)
    audit = read_csv_required(CAMPAIGN_AUDIT_PATH)

    ensure_columns(
        campaigns,
        ["campaign_id", "campaign_name", "campaign_type"],
        "campaigns",
    )
    ensure_columns(
        channels,
        ["campaign_id", "channel"],
        "campaign_channels",
    )
    ensure_columns(
        campaign_customers,
        [
            "campaign_id",
            "customer_id",
            "selection_date",
            "exposure_status",
            "exposure_date",
            "response_status",
            "response_date",
        ],
        "campaign_customers",
    )
    ensure_columns(
        exposures,
        [
            "exposure_id",
            "campaign_id",
            "customer_id",
            "exposure_datetime",
            "channel",
        ],
        "campaign_exposures",
    )
    ensure_columns(
        audit,
        [
            "campaign_id",
            "eligible_customers",
            "selected_customers",
            "exposed_customers",
            "responding_customers",
            "positive_responses",
            "neutral_responses",
            "negative_responses",
        ],
        "campaign_generation_audit",
    )

    campaigns["campaign_id"] = campaigns["campaign_id"].astype(str)
    channels["campaign_id"] = channels["campaign_id"].astype(str)
    campaign_customers["campaign_id"] = campaign_customers["campaign_id"].astype(str)
    exposures["campaign_id"] = exposures["campaign_id"].astype(str)
    audit["campaign_id"] = audit["campaign_id"].astype(str)

    campaign_customers["customer_id"] = campaign_customers["customer_id"].astype(str)
    exposures["customer_id"] = exposures["customer_id"].astype(str)

    campaign_customers["selection_date"] = pd.to_datetime(
        campaign_customers["selection_date"], errors="coerce"
    )
    campaign_customers["exposure_date"] = pd.to_datetime(
        campaign_customers["exposure_date"], errors="coerce"
    )
    campaign_customers["response_date"] = pd.to_datetime(
        campaign_customers["response_date"], errors="coerce"
    )
    exposures["exposure_datetime"] = pd.to_datetime(
        exposures["exposure_datetime"], errors="coerce"
    )

    audit = audit.merge(
        campaigns[["campaign_id", "campaign_name", "campaign_type"]],
        on="campaign_id",
        how="left",
        suffixes=("", "_master"),
    )

    if "campaign_name_master" in audit.columns:
        audit["campaign_name"] = audit["campaign_name"].fillna(
            audit["campaign_name_master"]
        )
        audit = audit.drop(columns=["campaign_name_master"])

    if "campaign_type_master" in audit.columns:
        if "campaign_type" not in audit.columns:
            audit["campaign_type"] = audit["campaign_type_master"]
        else:
            audit["campaign_type"] = audit["campaign_type"].fillna(
                audit["campaign_type_master"]
            )
        audit = audit.drop(columns=["campaign_type_master"])

    audit = audit.sort_values("campaign_id").reset_index(drop=True)

    return campaigns, channels, campaign_customers, exposures, audit


def add_production_rates(
    audit: pd.DataFrame,
    exposures: pd.DataFrame,
) -> pd.DataFrame:
    out = audit.copy()

    for col in [
        "eligible_customers",
        "selected_customers",
        "exposed_customers",
        "responding_customers",
        "positive_responses",
        "neutral_responses",
        "negative_responses",
    ]:
        out[col] = pd.to_numeric(out[col], errors="coerce").fillna(0).astype(int)

    out["selection_rate_prod"] = (
        out["selected_customers"] / out["eligible_customers"].clip(lower=1)
    )
    out["exposure_rate_prod"] = (
        out["exposed_customers"] / out["selected_customers"].clip(lower=1)
    )
    out["response_rate_prod"] = (
        out["responding_customers"] / out["exposed_customers"].clip(lower=1)
    )

    out["positive_share_responders"] = (
        out["positive_responses"] / out["responding_customers"].clip(lower=1)
    )
    out["neutral_share_responders"] = (
        out["neutral_responses"] / out["responding_customers"].clip(lower=1)
    )
    out["negative_share_responders"] = (
        out["negative_responses"] / out["responding_customers"].clip(lower=1)
    )

    event_counts = (
        exposures.groupby("campaign_id", observed=True)
        .size()
        .rename("exposure_events")
    )
    out = out.merge(event_counts, on="campaign_id", how="left")
    out["exposure_events"] = out["exposure_events"].fillna(0).astype(int)

    out["events_per_exposed_prod"] = (
        out["exposure_events"] / out["exposed_customers"].clip(lower=1)
    )
    out["extra_events_per_exposed_prod"] = np.clip(
        out["events_per_exposed_prod"] - 1.0,
        0.0,
        None,
    )

    return out


# =============================================================================
# Lightweight Monte Carlo
# =============================================================================

def simulate_worlds(
    production: pd.DataFrame,
    worlds: int,
    seed: int,
):
    n_campaigns = len(production)
    eligible = production["eligible_customers"].to_numpy(dtype=int)

    selection_mean = production["selection_rate_prod"].to_numpy(dtype=float)
    exposure_mean = production["exposure_rate_prod"].to_numpy(dtype=float)
    response_mean = production["response_rate_prod"].to_numpy(dtype=float)

    positive_share = production["positive_share_responders"].to_numpy(dtype=float)
    neutral_share = production["neutral_share_responders"].to_numpy(dtype=float)
    negative_share = production["negative_share_responders"].to_numpy(dtype=float)

    extra_events_mean = production["extra_events_per_exposed_prod"].to_numpy(
        dtype=float
    )

    rng_sel_p = make_rng(seed, RNG_STREAMS["selection_probability"])
    rng_sel = make_rng(seed, RNG_STREAMS["selection_realization"])
    rng_exp_p = make_rng(seed, RNG_STREAMS["exposure_probability"])
    rng_exp = make_rng(seed, RNG_STREAMS["exposure_realization"])
    rng_rsp_p = make_rng(seed, RNG_STREAMS["response_probability"])
    rng_rsp = make_rng(seed, RNG_STREAMS["response_realization"])
    rng_mix = make_rng(seed, RNG_STREAMS["response_mix"])
    rng_mix_real = make_rng(seed, RNG_STREAMS["response_mix_realization"])
    rng_follow_p = make_rng(seed, RNG_STREAMS["followup_intensity"])
    rng_follow = make_rng(seed, RNG_STREAMS["followup_realization"])

    selected = np.zeros((worlds, n_campaigns), dtype=np.int32)
    exposed = np.zeros((worlds, n_campaigns), dtype=np.int32)
    responding = np.zeros((worlds, n_campaigns), dtype=np.int32)
    positive = np.zeros((worlds, n_campaigns), dtype=np.int32)
    neutral = np.zeros((worlds, n_campaigns), dtype=np.int32)
    negative = np.zeros((worlds, n_campaigns), dtype=np.int32)
    exposure_events = np.zeros((worlds, n_campaigns), dtype=np.int32)

    for j in range(n_campaigns):
        a, b = beta_shapes(selection_mean[j], SELECTION_CONCENTRATION)
        p_sel = rng_sel_p.beta(a, b, size=worlds)
        selected[:, j] = rng_sel.binomial(eligible[j], p_sel)

        a, b = beta_shapes(exposure_mean[j], EXPOSURE_CONCENTRATION)
        p_exp = rng_exp_p.beta(a, b, size=worlds)
        exposed[:, j] = rng_exp.binomial(selected[:, j], p_exp)

        a, b = beta_shapes(response_mean[j], RESPONSE_CONCENTRATION)
        p_rsp = rng_rsp_p.beta(a, b, size=worlds)
        responding[:, j] = rng_rsp.binomial(exposed[:, j], p_rsp)

        # Response composition among responders. Add a weak symmetric prior so
        # small campaigns can produce categories not observed in one production
        # realization, while still remaining centered on the production mix.
        mix = np.array(
            [positive_share[j], neutral_share[j], negative_share[j]],
            dtype=float,
        )
        if mix.sum() <= 0:
            mix = np.array([0.50, 0.30, 0.20], dtype=float)
        mix = mix / mix.sum()

        alpha = 1.0 + RESPONSE_MIX_CONCENTRATION * mix
        world_mix = rng_mix.dirichlet(alpha, size=worlds)

        for w in range(worlds):
            n_resp = int(responding[w, j])
            if n_resp <= 0:
                continue
            draw = rng_mix_real.multinomial(n_resp, world_mix[w])
            positive[w, j] = int(draw[0])
            neutral[w, j] = int(draw[1])
            negative[w, j] = int(draw[2])

        # Extra successful contacts beyond the first exposure. Model the mean
        # extra-contact intensity with Gamma heterogeneity, then draw Poisson
        # extra events conditional on the number of exposed relationships.
        mean_extra = float(max(extra_events_mean[j], 0.0))
        if mean_extra <= EPS:
            exposure_events[:, j] = exposed[:, j]
        else:
            shape = FOLLOWUP_CONCENTRATION
            scale = mean_extra / FOLLOWUP_CONCENTRATION
            lambda_extra = rng_follow_p.gamma(shape, scale, size=worlds)
            extra = rng_follow.poisson(exposed[:, j] * lambda_extra)
            exposure_events[:, j] = exposed[:, j] + extra

    return {
        "selected": selected,
        "exposed": exposed,
        "responding": responding,
        "positive": positive,
        "neutral": neutral,
        "negative": negative,
        "exposure_events": exposure_events,
        "eligible": eligible,
    }


# =============================================================================
# Monte Carlo summaries
# =============================================================================

def build_world_summary(sim: dict) -> pd.DataFrame:
    selected = sim["selected"]
    exposed = sim["exposed"]
    responding = sim["responding"]
    positive = sim["positive"]
    neutral = sim["neutral"]
    negative = sim["negative"]
    exposure_events = sim["exposure_events"]
    eligible = sim["eligible"]

    worlds = selected.shape[0]

    total_eligible = np.full(worlds, eligible.sum(), dtype=float)
    total_selected = selected.sum(axis=1)
    total_exposed = exposed.sum(axis=1)
    total_responding = responding.sum(axis=1)
    total_positive = positive.sum(axis=1)
    total_neutral = neutral.sum(axis=1)
    total_negative = negative.sum(axis=1)
    total_events = exposure_events.sum(axis=1)

    return pd.DataFrame(
        {
            "world": np.arange(1, worlds + 1),
            "eligible_relationships": total_eligible.astype(int),
            "selected_relationships": total_selected,
            "exposed_relationships": total_exposed,
            "responding_relationships": total_responding,
            "positive_responses": total_positive,
            "neutral_responses": total_neutral,
            "negative_responses": total_negative,
            "exposure_events": total_events,
            "overall_selection_rate": safe_rate(total_selected, total_eligible),
            "overall_exposure_rate": safe_rate(total_exposed, total_selected),
            "overall_response_rate_exposed": safe_rate(
                total_responding, total_exposed
            ),
            "events_per_exposed_relationship": safe_rate(
                total_events, total_exposed
            ),
        }
    )


def build_campaign_summary(
    production: pd.DataFrame,
    sim: dict,
) -> pd.DataFrame:
    rows = []

    for j, row in production.reset_index(drop=True).iterrows():
        selected = sim["selected"][:, j]
        exposed = sim["exposed"][:, j]
        responding = sim["responding"][:, j]
        positive = sim["positive"][:, j]
        neutral = sim["neutral"][:, j]
        negative = sim["negative"][:, j]
        events = sim["exposure_events"][:, j]

        eligible = np.full_like(selected, int(row["eligible_customers"]))

        selection_rate = safe_rate(selected, eligible)
        exposure_rate = safe_rate(exposed, selected)
        response_rate = safe_rate(responding, exposed)
        events_per_exposed = safe_rate(events, exposed)

        rows.append(
            {
                "campaign_id": row["campaign_id"],
                "campaign_name": row["campaign_name"],
                "campaign_type": row["campaign_type"],
                "eligible_customers": int(row["eligible_customers"]),
                "production_selection_rate": row["selection_rate_prod"],
                "selection_mean": float(selection_rate.mean()),
                "selection_p05": q(selection_rate, 0.05),
                "selection_p50": q(selection_rate, 0.50),
                "selection_p95": q(selection_rate, 0.95),
                "production_exposure_rate": row["exposure_rate_prod"],
                "exposure_mean": float(exposure_rate.mean()),
                "exposure_p05": q(exposure_rate, 0.05),
                "exposure_p50": q(exposure_rate, 0.50),
                "exposure_p95": q(exposure_rate, 0.95),
                "production_response_rate": row["response_rate_prod"],
                "response_mean": float(response_rate.mean()),
                "response_p05": q(response_rate, 0.05),
                "response_p50": q(response_rate, 0.50),
                "response_p95": q(response_rate, 0.95),
                "production_events_per_exposed": row["events_per_exposed_prod"],
                "events_per_exposed_mean": float(events_per_exposed.mean()),
                "events_per_exposed_p05": q(events_per_exposed, 0.05),
                "events_per_exposed_p50": q(events_per_exposed, 0.50),
                "events_per_exposed_p95": q(events_per_exposed, 0.95),
                "zero_selected_world_share": float(np.mean(selected == 0)),
                "zero_exposed_world_share": float(np.mean(exposed == 0)),
                "zero_response_world_share": float(np.mean(responding == 0)),
                "all_selected_exposed_world_share": float(
                    np.mean((selected > 0) & (exposed == selected))
                ),
                "positive_mean": float(positive.mean()),
                "neutral_mean": float(neutral.mean()),
                "negative_mean": float(negative.mean()),
            }
        )

    return pd.DataFrame(rows)


# =============================================================================
# Production diagnostics
# =============================================================================

def production_diagnostics(
    campaign_customers: pd.DataFrame,
    exposures: pd.DataFrame,
    channels: pd.DataFrame,
) -> pd.DataFrame:
    rows = []

    selected_per_customer = (
        campaign_customers.groupby("customer_id", observed=True)
        .size()
        .rename("campaign_selections")
    )

    exposed_pairs = campaign_customers[
        campaign_customers["exposure_status"].astype(str).str.upper() == "EXPOSED"
    ]
    exposed_per_customer = (
        exposed_pairs.groupby("customer_id", observed=True)
        .size()
        .rename("campaign_exposures")
    )

    event_per_customer = (
        exposures.groupby("customer_id", observed=True)
        .size()
        .rename("exposure_events")
    )

    for name, s in [
        ("campaign_selections_per_selected_customer", selected_per_customer),
        ("campaign_relationships_per_exposed_customer", exposed_per_customer),
        ("exposure_events_per_contacted_customer", event_per_customer),
    ]:
        values = s.to_numpy(dtype=float)
        rows.append(
            {
                "diagnostic": name,
                "n_customers": len(values),
                "mean": float(values.mean()) if len(values) else 0.0,
                "p50": q(values, 0.50) if len(values) else 0.0,
                "p95": q(values, 0.95) if len(values) else 0.0,
                "p99": q(values, 0.99) if len(values) else 0.0,
                "max": float(values.max()) if len(values) else 0.0,
                "share_ge_2": float(np.mean(values >= 2)) if len(values) else 0.0,
                "share_ge_3": float(np.mean(values >= 3)) if len(values) else 0.0,
                "share_ge_5": float(np.mean(values >= 5)) if len(values) else 0.0,
            }
        )

    # Channel mix diagnostics.
    if len(exposures):
        channel_counts = exposures["channel"].astype(str).str.upper().value_counts()
        total = int(channel_counts.sum())
        for channel, count in channel_counts.items():
            rows.append(
                {
                    "diagnostic": f"channel_share_{channel}",
                    "n_customers": np.nan,
                    "mean": count / total,
                    "p50": np.nan,
                    "p95": np.nan,
                    "p99": np.nan,
                    "max": np.nan,
                    "share_ge_2": np.nan,
                    "share_ge_3": np.nan,
                    "share_ge_5": np.nan,
                }
            )

    # Multi-channel relationships.
    if len(exposures):
        pair_channel_count = (
            exposures.groupby(["campaign_id", "customer_id"], observed=True)["channel"]
            .nunique()
        )
        rows.append(
            {
                "diagnostic": "channels_per_exposed_relationship",
                "n_customers": len(pair_channel_count),
                "mean": float(pair_channel_count.mean()),
                "p50": q(pair_channel_count.to_numpy(dtype=float), 0.50),
                "p95": q(pair_channel_count.to_numpy(dtype=float), 0.95),
                "p99": q(pair_channel_count.to_numpy(dtype=float), 0.99),
                "max": float(pair_channel_count.max()),
                "share_ge_2": float(np.mean(pair_channel_count >= 2)),
                "share_ge_3": float(np.mean(pair_channel_count >= 3)),
                "share_ge_5": float(np.mean(pair_channel_count >= 5)),
            }
        )

    # Authorized-channel coverage is a structural production diagnostic.
    authorized = set(
        zip(
            channels["campaign_id"].astype(str),
            channels["channel"].astype(str).str.upper(),
        )
    )
    actual = set(
        zip(
            exposures["campaign_id"].astype(str),
            exposures["channel"].astype(str).str.upper(),
        )
    )
    unauthorized = actual - authorized

    rows.append(
        {
            "diagnostic": "unauthorized_campaign_channel_pairs",
            "n_customers": np.nan,
            "mean": float(len(unauthorized)),
            "p50": np.nan,
            "p95": np.nan,
            "p99": np.nan,
            "max": np.nan,
            "share_ge_2": np.nan,
            "share_ge_3": np.nan,
            "share_ge_5": np.nan,
        }
    )

    return pd.DataFrame(rows)


# =============================================================================
# Guardrails
# =============================================================================

def build_guardrails(
    production: pd.DataFrame,
    world_summary: pd.DataFrame,
    campaign_summary: pd.DataFrame,
    diagnostics: pd.DataFrame,
) -> pd.DataFrame:
    checks = []

    def add(name: str, passed: bool, observed, rule: str):
        checks.append(
            {
                "check": name,
                "status": "PASS" if passed else "FAIL",
                "observed": observed,
                "rule": rule,
            }
        )

    exp = world_summary["overall_exposure_rate"].to_numpy()
    rsp = world_summary["overall_response_rate_exposed"].to_numpy()
    evp = world_summary["events_per_exposed_relationship"].to_numpy()
    sel = world_summary["overall_selection_rate"].to_numpy()

    # Broad model-level guardrails. These are not calibration targets.
    add(
        "overall_selection_distribution_plausible",
        q(sel, 0.05) > 0.05 and q(sel, 0.95) < 0.65,
        f"P05={pct(q(sel, 0.05))}, P95={pct(q(sel, 0.95))}",
        "P05 > 5% and P95 < 65%",
    )
    add(
        "overall_exposure_distribution_plausible",
        q(exp, 0.05) > 0.60 and q(exp, 0.95) < 0.97,
        f"P05={pct(q(exp, 0.05))}, P95={pct(q(exp, 0.95))}",
        "P05 > 60% and P95 < 97%",
    )
    add(
        "overall_response_distribution_plausible",
        q(rsp, 0.05) > 0.03 and q(rsp, 0.95) < 0.40,
        f"P05={pct(q(rsp, 0.05))}, P95={pct(q(rsp, 0.95))}",
        "P05 > 3% and P95 < 40%",
    )
    add(
        "contact_frequency_plausible",
        q(evp, 0.05) >= 1.0 and q(evp, 0.95) < 3.5,
        f"P05={q(evp, 0.05):.3f}, P95={q(evp, 0.95):.3f}",
        "P05 >= 1.0 and P95 < 3.5 exposure events per exposed relationship",
    )

    # Large campaigns should not frequently disappear entirely.
    large = campaign_summary[campaign_summary["eligible_customers"] >= 500]
    add(
        "large_campaigns_rarely_zero_selection",
        bool((large["zero_selected_world_share"] < 0.01).all()),
        f"max zero-selected share={large['zero_selected_world_share'].max():.4f}",
        "Eligible >= 500: zero-selected world share < 1%",
    )
    add(
        "large_campaigns_rarely_zero_exposure",
        bool((large["zero_exposed_world_share"] < 0.01).all()),
        f"max zero-exposed share={large['zero_exposed_world_share'].max():.4f}",
        "Eligible >= 500: zero-exposed world share < 1%",
    )

    # Small campaigns are allowed to be noisy. We explicitly require that at
    # least one small campaign has meaningful zero-response probability, which
    # protects against accidental deterministic smoothing.
    small = campaign_summary[campaign_summary["eligible_customers"] < 100]
    if len(small):
        max_zero_resp = float(small["zero_response_world_share"].max())
        add(
            "small_campaign_volatility_preserved",
            max_zero_resp >= 0.05,
            f"max zero-response world share={max_zero_resp:.4f}",
            "At least one eligible<100 campaign has >=5% zero-response worlds",
        )
    else:
        add(
            "small_campaign_volatility_preserved",
            True,
            "No eligible<100 campaigns in production",
            "Not applicable",
        )

    # Exposure must not collapse back to the V1.0.1 near-certainty regime.
    large_exp_p95 = float(
        campaign_summary.loc[
            campaign_summary["eligible_customers"] >= 500,
            "exposure_p95",
        ].median()
    )
    add(
        "delivery_not_near_deterministic",
        large_exp_p95 < 0.97,
        f"median large-campaign exposure P95={pct(large_exp_p95)}",
        "Median large-campaign exposure P95 < 97%",
    )

    # Production overlap / concentration.
    diag_map = diagnostics.set_index("diagnostic")["mean"].to_dict()
    unauthorized = float(diag_map.get("unauthorized_campaign_channel_pairs", 0.0))
    add(
        "authorized_channels_only",
        unauthorized == 0.0,
        f"unauthorized pairs={int(unauthorized)}",
        "No actual campaign/channel pair may be unauthorized",
    )

    exposure_customer_diag = diagnostics[
        diagnostics["diagnostic"] == "exposure_events_per_contacted_customer"
    ]
    if len(exposure_customer_diag):
        p99 = float(exposure_customer_diag.iloc[0]["p99"])
        max_events = float(exposure_customer_diag.iloc[0]["max"])
        add(
            "customer_contact_concentration_plausible",
            p99 < 12 and max_events < 25,
            f"P99={p99:.1f}, max={max_events:.0f}",
            "P99 < 12 and max < 25 exposure events per contacted customer",
        )

    multi_diag = diagnostics[
        diagnostics["diagnostic"] == "channels_per_exposed_relationship"
    ]
    if len(multi_diag):
        share_multi = float(multi_diag.iloc[0]["share_ge_2"])
        add(
            "multichannel_not_universal",
            share_multi < 0.75,
            f"share with >=2 channels={pct(share_multi)}",
            "Less than 75% of exposed relationships use multiple channels",
        )

    # Structural production consistency from aggregate counts.
    count_identity = bool(
        (
            production["positive_responses"]
            + production["neutral_responses"]
            + production["negative_responses"]
            == production["responding_customers"]
        ).all()
    )
    add(
        "response_composition_reconciles",
        count_identity,
        "campaign-level response categories checked",
        "Positive + neutral + negative = responding customers",
    )

    return pd.DataFrame(checks)


# =============================================================================
# Console output
# =============================================================================

def print_header(worlds: int, seed: int, production: pd.DataFrame) -> None:
    print("=" * 104)
    print("BTYT CAMPAIGN BEHAVIORAL LAYER — MONTE CARLO AUDIT V1.0.0")
    print("=" * 104)
    print(f"Worlds simulated:             {worlds:,}")
    print(f"Audit seed:                   {seed}")
    print(f"Campaigns:                    {len(production)}")
    print(
        f"Production eligible rels:     "
        f"{int(production['eligible_customers'].sum()):,}"
    )
    print(
        f"Production selected rels:     "
        f"{int(production['selected_customers'].sum()):,}"
    )
    print(
        f"Production exposed rels:      "
        f"{int(production['exposed_customers'].sum()):,}"
    )
    print()


def print_world_distribution(world_summary: pd.DataFrame) -> None:
    print("=" * 104)
    print("WORLD DISTRIBUTION SUMMARY")
    print("=" * 104)

    metrics = [
        ("overall_selection_rate", "Overall selection rate", True),
        ("overall_exposure_rate", "Overall exposure rate", True),
        ("overall_response_rate_exposed", "Response rate / exposed", True),
        ("events_per_exposed_relationship", "Exposure events / exposed", False),
        ("selected_relationships", "Selected relationships", False),
        ("exposed_relationships", "Exposed relationships", False),
        ("responding_relationships", "Observed responses", False),
    ]

    print(
        f"{'Metric':<31} {'Mean':>11} {'P05':>11} "
        f"{'Median':>11} {'P95':>11}"
    )

    for col, label, as_percent in metrics:
        arr = world_summary[col].to_numpy(dtype=float)
        vals = [
            float(arr.mean()),
            q(arr, 0.05),
            q(arr, 0.50),
            q(arr, 0.95),
        ]
        if as_percent:
            fmt = [pct(v) for v in vals]
        else:
            fmt = [f"{v:,.3f}" if "events" in col else f"{v:,.0f}" for v in vals]

        print(
            f"{label:<31} {fmt[0]:>11} {fmt[1]:>11} "
            f"{fmt[2]:>11} {fmt[3]:>11}"
        )
    print()


def print_campaign_distribution(summary: pd.DataFrame) -> None:
    print("=" * 104)
    print("CAMPAIGN DISTRIBUTION SUMMARY")
    print("=" * 104)
    print(
        f"{'ID':<5} {'Eligible':>8} "
        f"{'Sel mean':>9} {'Sel P05':>9} {'Sel P95':>9} "
        f"{'Exp mean':>9} {'Exp P05':>9} {'Exp P95':>9} "
        f"{'Rsp mean':>9} {'Rsp P05':>9} {'Rsp P95':>9} "
        f"{'% zero rsp':>10}"
    )

    for row in summary.itertuples(index=False):
        print(
            f"{row.campaign_id:<5} "
            f"{int(row.eligible_customers):>8,} "
            f"{pct(row.selection_mean):>9} "
            f"{pct(row.selection_p05):>9} "
            f"{pct(row.selection_p95):>9} "
            f"{pct(row.exposure_mean):>9} "
            f"{pct(row.exposure_p05):>9} "
            f"{pct(row.exposure_p95):>9} "
            f"{pct(row.response_mean):>9} "
            f"{pct(row.response_p05):>9} "
            f"{pct(row.response_p95):>9} "
            f"{pct(row.zero_response_world_share):>10}"
        )
    print()


def print_production_diagnostics(diagnostics: pd.DataFrame) -> None:
    print("=" * 104)
    print("PRODUCTION CUSTOMER / CHANNEL DIAGNOSTICS")
    print("=" * 104)

    main = diagnostics[
        diagnostics["diagnostic"].isin(
            [
                "campaign_selections_per_selected_customer",
                "campaign_relationships_per_exposed_customer",
                "exposure_events_per_contacted_customer",
                "channels_per_exposed_relationship",
            ]
        )
    ]

    print(
        f"{'Diagnostic':<48} {'Mean':>8} {'P50':>8} "
        f"{'P95':>8} {'P99':>8} {'Max':>8} {'>=2':>8}"
    )
    for row in main.itertuples(index=False):
        print(
            f"{row.diagnostic:<48} "
            f"{row.mean:>8.3f} "
            f"{row.p50:>8.2f} "
            f"{row.p95:>8.2f} "
            f"{row.p99:>8.2f} "
            f"{row.max:>8.0f} "
            f"{pct(row.share_ge_2):>8}"
        )

    channel_rows = diagnostics[
        diagnostics["diagnostic"].str.startswith("channel_share_")
    ].copy()

    if len(channel_rows):
        print()
        print("Exposure event channel mix:")
        for row in channel_rows.sort_values("mean", ascending=False).itertuples(index=False):
            channel = row.diagnostic.replace("channel_share_", "")
            print(f"  {channel:<16} {pct(row.mean)}")
    print()


def print_guardrails(guardrails: pd.DataFrame) -> bool:
    print("=" * 104)
    print("AUDIT GUARDRAILS")
    print("=" * 104)

    for row in guardrails.itertuples(index=False):
        print(
            f"  {row.check:<46} {row.status:<4}  "
            f"{row.observed}"
        )

    passed = bool((guardrails["status"] == "PASS").all())
    print()
    print(f"MONTE CARLO AUDIT: {'PASS' if passed else 'FAIL'}")
    return passed


# =============================================================================
# Save
# =============================================================================

def save_outputs(
    world_summary: pd.DataFrame,
    campaign_summary: pd.DataFrame,
    guardrails: pd.DataFrame,
    diagnostics: pd.DataFrame,
) -> None:
    DATA_INTERIM.mkdir(parents=True, exist_ok=True)

    world_summary.to_csv(WORLD_SUMMARY_PATH, index=False)
    campaign_summary.to_csv(CAMPAIGN_SUMMARY_PATH, index=False)
    guardrails.to_csv(GUARDRAILS_PATH, index=False)
    diagnostics.to_csv(PRODUCTION_DIAGNOSTICS_PATH, index=False)

    print()
    print("Saved:")
    print(f"  {WORLD_SUMMARY_PATH}")
    print(f"  {CAMPAIGN_SUMMARY_PATH}")
    print(f"  {GUARDRAILS_PATH}")
    print(f"  {PRODUCTION_DIAGNOSTICS_PATH}")


# =============================================================================
# Main
# =============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="BTYT Campaign Behavioral Layer Monte Carlo Audit V1.0.0"
    )
    parser.add_argument(
        "--worlds",
        type=int,
        default=DEFAULT_WORLDS,
        help=f"Monte Carlo worlds. Default: {DEFAULT_WORLDS:,}",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_AUDIT_SEED,
        help=f"Audit seed. Default: {DEFAULT_AUDIT_SEED}",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.worlds <= 0:
        raise ValueError("--worlds must be a positive integer.")

    campaigns, channels, campaign_customers, exposures, audit = load_inputs()
    production = add_production_rates(audit, exposures)

    print_header(args.worlds, args.seed, production)
    print("Running lightweight hierarchical Monte Carlo...")
    sim = simulate_worlds(production, args.worlds, args.seed)

    world_summary = build_world_summary(sim)
    campaign_summary = build_campaign_summary(production, sim)
    diagnostics = production_diagnostics(
        campaign_customers,
        exposures,
        channels,
    )
    guardrails = build_guardrails(
        production,
        world_summary,
        campaign_summary,
        diagnostics,
    )

    print_world_distribution(world_summary)
    print_campaign_distribution(campaign_summary)
    print_production_diagnostics(diagnostics)
    passed = print_guardrails(guardrails)

    save_outputs(
        world_summary,
        campaign_summary,
        guardrails,
        diagnostics,
    )

    print()
    print("=" * 104)
    print(
        f"BTYT CAMPAIGN MONTE CARLO AUDIT V{ENGINE_VERSION}: "
        f"{'PASS' if passed else 'FAIL'}"
    )
    print("=" * 104)
    print("No production campaign table was modified.")
    print("No downstream banking conversion was manufactured.")

    if not passed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
